<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alejandro Feria González, aferiag@unal.edu.co">
<meta name="author" content="Andres Felipe Arismendi Alzate, aarismendi@unal.edu.co">
<meta name="author" content="Abraham David Miguel Cardenas, amiguel@unal.edu.co">
<meta name="author" content="Santiago Molina Munoz, smolinam@unal.edu.co">
<meta name="dcterms.date" content="2025-06-30">

<title>Sistema Inteligente Integrado para Predicción, Clasificación y Recomendación en la Empresa de Transporte – Redes Neuronales y Algoritmos Bioinspirados.</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ebd8daedd9a06b75d3ddf6b0552b5a29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script src="../../site_libs/quarto-contrib/videojs/video.min.js"></script>
<link href="../../site_libs/quarto-contrib/videojs/video-js.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="custom.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Redes Neuronales y Algoritmos Bioinspirados.</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-right">
      <h1 class="title">Sistema Inteligente Integrado para Predicción, Clasificación y Recomendación en la Empresa de Transporte</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Redes Neuronales</div>
                <div class="quarto-category">Algoritmos bioinspirados</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta column-page-right">

      <div>
      <div class="quarto-title-meta-heading">Authors</div>
      <div class="quarto-title-meta-contents">
               <p>Alejandro Feria González, aferiag@unal.edu.co </p>
               <p>Andres Felipe Arismendi Alzate, aarismendi@unal.edu.co </p>
               <p>Abraham David Miguel Cardenas, amiguel@unal.edu.co </p>
               <p>Santiago Molina Munoz, smolinam@unal.edu.co </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 30, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenido</h2>
   
  <ul>
  <li><a href="#resumen-ejecutivo" id="toc-resumen-ejecutivo" class="nav-link active" data-scroll-target="#resumen-ejecutivo"><span class="header-section-number">1</span> Resumen Ejecutivo</a></li>
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción"><span class="header-section-number">2</span> Introducción</a>
  <ul class="collapse">
  <li><a href="#objetivo-general" id="toc-objetivo-general" class="nav-link" data-scroll-target="#objetivo-general"><span class="header-section-number">2.1</span> Objetivo General</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos Específicos</a></li>
  <li><a href="#alcances" id="toc-alcances" class="nav-link" data-scroll-target="#alcances"><span class="header-section-number">2.3</span> Alcances</a></li>
  <li><a href="#limitaciones" id="toc-limitaciones" class="nav-link" data-scroll-target="#limitaciones"><span class="header-section-number">2.4</span> Limitaciones</a></li>
  </ul></li>
  <li><a href="#metodología" id="toc-metodología" class="nav-link" data-scroll-target="#metodología"><span class="header-section-number">3</span> Metodología</a>
  <ul class="collapse">
  <li><a href="#explicación-de-conceptos-clave" id="toc-explicación-de-conceptos-clave" class="nav-link" data-scroll-target="#explicación-de-conceptos-clave"><span class="header-section-number">3.1</span> Explicación de Conceptos Clave</a></li>
  <li><a href="#enfoque-general-del-proyecto" id="toc-enfoque-general-del-proyecto" class="nav-link" data-scroll-target="#enfoque-general-del-proyecto"><span class="header-section-number">3.2</span> Enfoque General del Proyecto</a></li>
  <li><a href="#fases-del-proyecto" id="toc-fases-del-proyecto" class="nav-link" data-scroll-target="#fases-del-proyecto"><span class="header-section-number">3.3</span> Fases del Proyecto</a></li>
  <li><a href="#herramientas-y-tecnologías-utilizadas" id="toc-herramientas-y-tecnologías-utilizadas" class="nav-link" data-scroll-target="#herramientas-y-tecnologías-utilizadas"><span class="header-section-number">3.4</span> Herramientas y Tecnologías Utilizadas</a></li>
  </ul></li>
  <li><a href="#desarrollo-técnico-por-módulo" id="toc-desarrollo-técnico-por-módulo" class="nav-link" data-scroll-target="#desarrollo-técnico-por-módulo"><span class="header-section-number">4</span> Desarrollo Técnico por Módulo</a>
  <ul class="collapse">
  <li><a href="#módulo-1-predicción-de-demanda-de-transporte" id="toc-módulo-1-predicción-de-demanda-de-transporte" class="nav-link" data-scroll-target="#módulo-1-predicción-de-demanda-de-transporte"><span class="header-section-number">4.1</span> Módulo 1: Predicción de Demanda de Transporte</a>
  <ul class="collapse">
  <li><a href="#descripción-del-problema" id="toc-descripción-del-problema" class="nav-link" data-scroll-target="#descripción-del-problema"><span class="header-section-number">4.1.1</span> Descripción del Problema</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset"><span class="header-section-number">4.1.2</span> Dataset</a></li>
  <li><a href="#preprocesamiento" id="toc-preprocesamiento" class="nav-link" data-scroll-target="#preprocesamiento"><span class="header-section-number">4.1.3</span> Preprocesamiento</a></li>
  <li><a href="#diseño-de-modelo" id="toc-diseño-de-modelo" class="nav-link" data-scroll-target="#diseño-de-modelo"><span class="header-section-number">4.1.4</span> Diseño de Modelo</a></li>
  <li><a href="#entrenamiento-del-modelo" id="toc-entrenamiento-del-modelo" class="nav-link" data-scroll-target="#entrenamiento-del-modelo"><span class="header-section-number">4.1.5</span> Entrenamiento del modelo</a></li>
  <li><a href="#evaluación-y-resultados" id="toc-evaluación-y-resultados" class="nav-link" data-scroll-target="#evaluación-y-resultados"><span class="header-section-number">4.1.6</span> Evaluación y Resultados</a></li>
  </ul></li>
  <li><a href="#módulo-2-clasificación-de-conducción-distractiva" id="toc-módulo-2-clasificación-de-conducción-distractiva" class="nav-link" data-scroll-target="#módulo-2-clasificación-de-conducción-distractiva"><span class="header-section-number">4.2</span> Módulo 2: Clasificación de Conducción Distractiva</a>
  <ul class="collapse">
  <li><a href="#descripción-del-problema-1" id="toc-descripción-del-problema-1" class="nav-link" data-scroll-target="#descripción-del-problema-1"><span class="header-section-number">4.2.1</span> Descripción del problema</a></li>
  <li><a href="#dataset-1" id="toc-dataset-1" class="nav-link" data-scroll-target="#dataset-1"><span class="header-section-number">4.2.2</span> Dataset</a></li>
  <li><a href="#preprocesamiento-1" id="toc-preprocesamiento-1" class="nav-link" data-scroll-target="#preprocesamiento-1"><span class="header-section-number">4.2.3</span> Preprocesamiento:</a></li>
  <li><a href="#diseño-de-modelo-1" id="toc-diseño-de-modelo-1" class="nav-link" data-scroll-target="#diseño-de-modelo-1"><span class="header-section-number">4.2.4</span> Diseño de Modelo</a></li>
  <li><a href="#evaluación" id="toc-evaluación" class="nav-link" data-scroll-target="#evaluación"><span class="header-section-number">4.2.5</span> Evaluación</a></li>
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados"><span class="header-section-number">4.2.6</span> Resultados</a></li>
  </ul></li>
  <li><a href="#módulo-3-recomendación-de-destinos-de-viaje" id="toc-módulo-3-recomendación-de-destinos-de-viaje" class="nav-link" data-scroll-target="#módulo-3-recomendación-de-destinos-de-viaje"><span class="header-section-number">4.3</span> Módulo 3: Recomendación de Destinos de Viaje</a>
  <ul class="collapse">
  <li><a href="#descripción-del-problema-2" id="toc-descripción-del-problema-2" class="nav-link" data-scroll-target="#descripción-del-problema-2"><span class="header-section-number">4.3.1</span> Descripción del Problema</a></li>
  <li><a href="#dataset-2" id="toc-dataset-2" class="nav-link" data-scroll-target="#dataset-2"><span class="header-section-number">4.3.2</span> Dataset</a></li>
  <li><a href="#preprocesamiento-2" id="toc-preprocesamiento-2" class="nav-link" data-scroll-target="#preprocesamiento-2"><span class="header-section-number">4.3.3</span> Preprocesamiento</a></li>
  <li><a href="#diseño-de-modelo-2" id="toc-diseño-de-modelo-2" class="nav-link" data-scroll-target="#diseño-de-modelo-2"><span class="header-section-number">4.3.4</span> Diseño de Modelo</a></li>
  <li><a href="#evaluación-y-resultados-1" id="toc-evaluación-y-resultados-1" class="nav-link" data-scroll-target="#evaluación-y-resultados-1"><span class="header-section-number">4.3.5</span> Evaluación y Resultados</a></li>
  <li><a href="#ejemplos-de-recomendaciones-generadas" id="toc-ejemplos-de-recomendaciones-generadas" class="nav-link" data-scroll-target="#ejemplos-de-recomendaciones-generadas"><span class="header-section-number">4.3.6</span> Ejemplos de recomendaciones generadas</a></li>
  <li><a href="#análisis-de-la-efectividad-de-las-recomendaciones" id="toc-análisis-de-la-efectividad-de-las-recomendaciones" class="nav-link" data-scroll-target="#análisis-de-la-efectividad-de-las-recomendaciones"><span class="header-section-number">4.3.7</span> Análisis de la efectividad de las recomendaciones:</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#herramienta-web" id="toc-herramienta-web" class="nav-link" data-scroll-target="#herramienta-web"><span class="header-section-number">5</span> Herramienta Web</a>
  <ul class="collapse">
  <li><a href="#descripción-de-la-interfaz" id="toc-descripción-de-la-interfaz" class="nav-link" data-scroll-target="#descripción-de-la-interfaz"><span class="header-section-number">5.1</span> Descripción de la interfaz</a></li>
  <li><a href="#funcionalidades" id="toc-funcionalidades" class="nav-link" data-scroll-target="#funcionalidades"><span class="header-section-number">5.2</span> Funcionalidades:</a>
  <ul class="collapse">
  <li><a href="#módulo-de-predicción-de-demanda" id="toc-módulo-de-predicción-de-demanda" class="nav-link" data-scroll-target="#módulo-de-predicción-de-demanda"><span class="header-section-number">5.2.1</span> Módulo de Predicción de Demanda</a></li>
  <li><a href="#módulo-de-clasificación-de-conducción-distractiva" id="toc-módulo-de-clasificación-de-conducción-distractiva" class="nav-link" data-scroll-target="#módulo-de-clasificación-de-conducción-distractiva"><span class="header-section-number">5.2.2</span> Módulo de Clasificación de Conducción Distractiva</a></li>
  <li><a href="#módulo-de-recomendación-de-destinos-de-viaje" id="toc-módulo-de-recomendación-de-destinos-de-viaje" class="nav-link" data-scroll-target="#módulo-de-recomendación-de-destinos-de-viaje"><span class="header-section-number">5.2.3</span> Módulo de Recomendación de Destinos de Viaje</a></li>
  </ul></li>
  <li><a href="#tecnologías-utilizadas" id="toc-tecnologías-utilizadas" class="nav-link" data-scroll-target="#tecnologías-utilizadas"><span class="header-section-number">5.3</span> Tecnologías utilizadas</a></li>
  </ul></li>
  <li><a href="#resultados-generales-y-discusión" id="toc-resultados-generales-y-discusión" class="nav-link" data-scroll-target="#resultados-generales-y-discusión"><span class="header-section-number">6</span> Resultados Generales y Discusión</a>
  <ul class="collapse">
  <li><a href="#análisis-de-resultados" id="toc-análisis-de-resultados" class="nav-link" data-scroll-target="#análisis-de-resultados"><span class="header-section-number">6.1</span> Análisis de resultados</a></li>
  <li><a href="#comparación-con-trabajos-previos" id="toc-comparación-con-trabajos-previos" class="nav-link" data-scroll-target="#comparación-con-trabajos-previos"><span class="header-section-number">6.2</span> Comparación con trabajos previos:</a></li>
  <li><a href="#impacto-en-la-empresa-de-transporte" id="toc-impacto-en-la-empresa-de-transporte" class="nav-link" data-scroll-target="#impacto-en-la-empresa-de-transporte"><span class="header-section-number">6.3</span> Impacto en la empresa de transporte:</a></li>
  </ul></li>
  <li><a href="#conclusiones-y-recomendaciones" id="toc-conclusiones-y-recomendaciones" class="nav-link" data-scroll-target="#conclusiones-y-recomendaciones"><span class="header-section-number">7</span> Conclusiones y Recomendaciones</a>
  <ul class="collapse">
  <li><a href="#resumen-de-hallazgos" id="toc-resumen-de-hallazgos" class="nav-link" data-scroll-target="#resumen-de-hallazgos"><span class="header-section-number">7.1</span> Resumen de hallazgos:</a></li>
  <li><a href="#propuestas-futuras" id="toc-propuestas-futuras" class="nav-link" data-scroll-target="#propuestas-futuras"><span class="header-section-number">7.2</span> Propuestas futuras:</a></li>
  </ul></li>
  <li><a href="#aspectos-éticos-y-creatividad" id="toc-aspectos-éticos-y-creatividad" class="nav-link" data-scroll-target="#aspectos-éticos-y-creatividad"><span class="header-section-number">8</span> Aspectos Éticos y Creatividad</a>
  <ul class="collapse">
  <li><a href="#gestión-de-datos-y-privacidad" id="toc-gestión-de-datos-y-privacidad" class="nav-link" data-scroll-target="#gestión-de-datos-y-privacidad"><span class="header-section-number">8.1</span> Gestión de datos y privacidad:</a></li>
  <li><a href="#sesgos-en-los-modelos" id="toc-sesgos-en-los-modelos" class="nav-link" data-scroll-target="#sesgos-en-los-modelos"><span class="header-section-number">8.2</span> Sesgos en los modelos:</a></li>
  <li><a href="#creatividad" id="toc-creatividad" class="nav-link" data-scroll-target="#creatividad"><span class="header-section-number">8.3</span> Creatividad:</a></li>
  </ul></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía"><span class="header-section-number">9</span> Bibliografía</a></li>
  <li><a href="#anexos" id="toc-anexos" class="nav-link" data-scroll-target="#anexos"><span class="header-section-number">10</span> Anexos</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block column-page-right" id="quarto-document-content">




<nav id="TOC-body" role="doc-toc">
    <h2 id="toc-title">Tabla de contenido</h2>
   
  <ul>
  <li><a href="#resumen-ejecutivo" id="toc-resumen-ejecutivo"><span class="header-section-number">1</span> Resumen Ejecutivo</a></li>
  <li><a href="#introducción" id="toc-introducción"><span class="header-section-number">2</span> Introducción</a>
  <ul>
  <li><a href="#objetivo-general" id="toc-objetivo-general"><span class="header-section-number">2.1</span> Objetivo General</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos Específicos</a></li>
  <li><a href="#alcances" id="toc-alcances"><span class="header-section-number">2.3</span> Alcances</a></li>
  <li><a href="#limitaciones" id="toc-limitaciones"><span class="header-section-number">2.4</span> Limitaciones</a></li>
  </ul></li>
  <li><a href="#metodología" id="toc-metodología"><span class="header-section-number">3</span> Metodología</a>
  <ul>
  <li><a href="#explicación-de-conceptos-clave" id="toc-explicación-de-conceptos-clave"><span class="header-section-number">3.1</span> Explicación de Conceptos Clave</a></li>
  <li><a href="#enfoque-general-del-proyecto" id="toc-enfoque-general-del-proyecto"><span class="header-section-number">3.2</span> Enfoque General del Proyecto</a></li>
  <li><a href="#fases-del-proyecto" id="toc-fases-del-proyecto"><span class="header-section-number">3.3</span> Fases del Proyecto</a></li>
  <li><a href="#herramientas-y-tecnologías-utilizadas" id="toc-herramientas-y-tecnologías-utilizadas"><span class="header-section-number">3.4</span> Herramientas y Tecnologías Utilizadas</a></li>
  </ul></li>
  <li><a href="#desarrollo-técnico-por-módulo" id="toc-desarrollo-técnico-por-módulo"><span class="header-section-number">4</span> Desarrollo Técnico por Módulo</a>
  <ul>
  <li><a href="#módulo-1-predicción-de-demanda-de-transporte" id="toc-módulo-1-predicción-de-demanda-de-transporte"><span class="header-section-number">4.1</span> Módulo 1: Predicción de Demanda de Transporte</a>
  <ul>
  <li><a href="#descripción-del-problema" id="toc-descripción-del-problema"><span class="header-section-number">4.1.1</span> Descripción del Problema</a></li>
  <li><a href="#dataset" id="toc-dataset"><span class="header-section-number">4.1.2</span> Dataset</a></li>
  <li><a href="#preprocesamiento" id="toc-preprocesamiento"><span class="header-section-number">4.1.3</span> Preprocesamiento</a></li>
  <li><a href="#diseño-de-modelo" id="toc-diseño-de-modelo"><span class="header-section-number">4.1.4</span> Diseño de Modelo</a></li>
  <li><a href="#entrenamiento-del-modelo" id="toc-entrenamiento-del-modelo"><span class="header-section-number">4.1.5</span> Entrenamiento del modelo</a></li>
  <li><a href="#evaluación-y-resultados" id="toc-evaluación-y-resultados"><span class="header-section-number">4.1.6</span> Evaluación y Resultados</a></li>
  </ul></li>
  <li><a href="#módulo-2-clasificación-de-conducción-distractiva" id="toc-módulo-2-clasificación-de-conducción-distractiva"><span class="header-section-number">4.2</span> Módulo 2: Clasificación de Conducción Distractiva</a>
  <ul>
  <li><a href="#descripción-del-problema-1" id="toc-descripción-del-problema-1"><span class="header-section-number">4.2.1</span> Descripción del problema</a></li>
  <li><a href="#dataset-1" id="toc-dataset-1"><span class="header-section-number">4.2.2</span> Dataset</a></li>
  <li><a href="#preprocesamiento-1" id="toc-preprocesamiento-1"><span class="header-section-number">4.2.3</span> Preprocesamiento:</a></li>
  <li><a href="#diseño-de-modelo-1" id="toc-diseño-de-modelo-1"><span class="header-section-number">4.2.4</span> Diseño de Modelo</a></li>
  <li><a href="#evaluación" id="toc-evaluación"><span class="header-section-number">4.2.5</span> Evaluación</a></li>
  <li><a href="#resultados" id="toc-resultados"><span class="header-section-number">4.2.6</span> Resultados</a></li>
  </ul></li>
  <li><a href="#módulo-3-recomendación-de-destinos-de-viaje" id="toc-módulo-3-recomendación-de-destinos-de-viaje"><span class="header-section-number">4.3</span> Módulo 3: Recomendación de Destinos de Viaje</a>
  <ul>
  <li><a href="#descripción-del-problema-2" id="toc-descripción-del-problema-2"><span class="header-section-number">4.3.1</span> Descripción del Problema</a></li>
  <li><a href="#dataset-2" id="toc-dataset-2"><span class="header-section-number">4.3.2</span> Dataset</a></li>
  <li><a href="#preprocesamiento-2" id="toc-preprocesamiento-2"><span class="header-section-number">4.3.3</span> Preprocesamiento</a></li>
  <li><a href="#diseño-de-modelo-2" id="toc-diseño-de-modelo-2"><span class="header-section-number">4.3.4</span> Diseño de Modelo</a></li>
  <li><a href="#evaluación-y-resultados-1" id="toc-evaluación-y-resultados-1"><span class="header-section-number">4.3.5</span> Evaluación y Resultados</a></li>
  <li><a href="#ejemplos-de-recomendaciones-generadas" id="toc-ejemplos-de-recomendaciones-generadas"><span class="header-section-number">4.3.6</span> Ejemplos de recomendaciones generadas</a></li>
  <li><a href="#análisis-de-la-efectividad-de-las-recomendaciones" id="toc-análisis-de-la-efectividad-de-las-recomendaciones"><span class="header-section-number">4.3.7</span> Análisis de la efectividad de las recomendaciones:</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#herramienta-web" id="toc-herramienta-web"><span class="header-section-number">5</span> Herramienta Web</a>
  <ul>
  <li><a href="#descripción-de-la-interfaz" id="toc-descripción-de-la-interfaz"><span class="header-section-number">5.1</span> Descripción de la interfaz</a></li>
  <li><a href="#funcionalidades" id="toc-funcionalidades"><span class="header-section-number">5.2</span> Funcionalidades:</a>
  <ul>
  <li><a href="#módulo-de-predicción-de-demanda" id="toc-módulo-de-predicción-de-demanda"><span class="header-section-number">5.2.1</span> Módulo de Predicción de Demanda</a></li>
  <li><a href="#módulo-de-clasificación-de-conducción-distractiva" id="toc-módulo-de-clasificación-de-conducción-distractiva"><span class="header-section-number">5.2.2</span> Módulo de Clasificación de Conducción Distractiva</a></li>
  <li><a href="#módulo-de-recomendación-de-destinos-de-viaje" id="toc-módulo-de-recomendación-de-destinos-de-viaje"><span class="header-section-number">5.2.3</span> Módulo de Recomendación de Destinos de Viaje</a></li>
  </ul></li>
  <li><a href="#tecnologías-utilizadas" id="toc-tecnologías-utilizadas"><span class="header-section-number">5.3</span> Tecnologías utilizadas</a></li>
  </ul></li>
  <li><a href="#resultados-generales-y-discusión" id="toc-resultados-generales-y-discusión"><span class="header-section-number">6</span> Resultados Generales y Discusión</a>
  <ul>
  <li><a href="#análisis-de-resultados" id="toc-análisis-de-resultados"><span class="header-section-number">6.1</span> Análisis de resultados</a></li>
  <li><a href="#comparación-con-trabajos-previos" id="toc-comparación-con-trabajos-previos"><span class="header-section-number">6.2</span> Comparación con trabajos previos:</a></li>
  <li><a href="#impacto-en-la-empresa-de-transporte" id="toc-impacto-en-la-empresa-de-transporte"><span class="header-section-number">6.3</span> Impacto en la empresa de transporte:</a></li>
  </ul></li>
  <li><a href="#conclusiones-y-recomendaciones" id="toc-conclusiones-y-recomendaciones"><span class="header-section-number">7</span> Conclusiones y Recomendaciones</a>
  <ul>
  <li><a href="#resumen-de-hallazgos" id="toc-resumen-de-hallazgos"><span class="header-section-number">7.1</span> Resumen de hallazgos:</a></li>
  <li><a href="#propuestas-futuras" id="toc-propuestas-futuras"><span class="header-section-number">7.2</span> Propuestas futuras:</a></li>
  </ul></li>
  <li><a href="#aspectos-éticos-y-creatividad" id="toc-aspectos-éticos-y-creatividad"><span class="header-section-number">8</span> Aspectos Éticos y Creatividad</a>
  <ul>
  <li><a href="#gestión-de-datos-y-privacidad" id="toc-gestión-de-datos-y-privacidad"><span class="header-section-number">8.1</span> Gestión de datos y privacidad:</a></li>
  <li><a href="#sesgos-en-los-modelos" id="toc-sesgos-en-los-modelos"><span class="header-section-number">8.2</span> Sesgos en los modelos:</a></li>
  <li><a href="#creatividad" id="toc-creatividad"><span class="header-section-number">8.3</span> Creatividad:</a></li>
  </ul></li>
  <li><a href="#bibliografía" id="toc-bibliografía"><span class="header-section-number">9</span> Bibliografía</a></li>
  <li><a href="#anexos" id="toc-anexos"><span class="header-section-number">10</span> Anexos</a></li>
  </ul>
</nav>
<section id="resumen-ejecutivo" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Resumen Ejecutivo</h1>
<p>Este reporte detalla el desarrollo de un sistema inteligente basado en aprendizaje profundo, diseñado para abordar tres desafíos críticos en una empresa de transporte: la optimización de recursos mediante la predicción de demanda, la mejora de la seguridad vial a través de la clasificación de comportamientos distractivos en conductores, y la personalización de la experiencia del usuario con un sistema de recomendación de destinos.</p>
<p>El proyecto se centró en la creación de tres módulos: un modelo de series de tiempo para predecir la demanda de transporte con 30 días de antelación, un clasificador de imágenes para identificar conductas distractivas como el uso del teléfono móvil, y un sistema de recomendación que sugiere destinos personalizados a los usuarios basándose en su historial y preferencias. Todas estas soluciones se integraron en una herramienta web intuitiva creada con FastAPI. Para la realizacion de los modelos 2 y 3 se uso TensorFlow y Keras, mientras que el modelo de series de tiempo se implementó con PyTorch.</p>
<p>Los resultados preliminares demuestran la viabilidad y el potencial impacto del sistema. El modelo de predicción de demanda alcanzó un RMSE de [Valor de RMSE] y un MAE de [Valor de MAE], lo que permite una planificación más precisa de la asignación de vehículos y personal. El clasificador de conducción distractiva logró una precisión del [Porcentaje de Precisión]% en la detección de comportamientos de riesgo, contribuyendo significativamente a la seguridad. Finalmente, el sistema de recomendación generó recomendaciones pertinentes, con una Precision de [Valor de Precision] y Recall de [Valor de Recall].</p>
<p>En conclusión, este sistema inteligente representa un avance significativo en la eficiencia operativa, la seguridad vial y la experiencia del cliente para la empresa de transporte, sentando las bases para futuras optimizaciones y expansiones.</p>
</section>
<section id="introducción" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introducción</h1>
<p>La industria del transporte se encuentra en una constante evolución, enfrentando desafíos como la fluctuación impredecible de la demanda, la imperante necesidad de garantizar la seguridad vial y la creciente expectativa de los usuarios por servicios personalizados. En este contexto, las empresas buscan soluciones innovadoras que les permitan optimizar sus operaciones, mitigar riesgos, maximizar ganancias y fidelizar a sus clientes. El aprendizaje profundo (Deep Learning) emerge como una tecnología clave, capaz de procesar grandes volúmenes de datos complejos para extraer patrones y tomar decisiones inteligentes, que manualmente serían inviables.</p>
<p>El presente proyecto aborda estas problemáticas mediante el desarrollo de tres modulos para predicción, clasificación y recomendación.</p>
<section id="objetivo-general" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="objetivo-general"><span class="header-section-number">2.1</span> Objetivo General</h2>
<p>Desarrollar un sistema inteligente basado en aprendizaje profundo que integre la predicción de la demanda de transporte, la clasificación de comportamientos distractores de los conductores mediante imágenes, y un sistema de recomendaciones personalizadas para mejorar la eficiencia y seguridad de los servicios de transporte.</p>
</section>
<section id="objetivos-específicos" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="objetivos-específicos"><span class="header-section-number">2.2</span> Objetivos Específicos</h2>
<ul>
<li>Entrenar un modelo de series de tiempo utilizando los datos históricos de la empresa para predecir la demanda de transporte en rutas específicas durante los próximos 30 días.</li>
<li>Implementar un modelo de clasificación de imágenes para identificar comportamientos distractores de los conductores, como el uso de teléfonos móviles o somnolencia.</li>
<li>Desarrollar un sistema de recomendaciones personalizadas para sugerir destinos de viaje en función del historial de viajes y las preferencias de los usuarios de la empresa.</li>
<li>Construir una herramienta web que integre todas las soluciones desarrolladas, permitiendo visualizar los resultados y probar los modelos de predicción, clasificación y recomendación.</li>
<li>Documentar el proceso de desarrollo en un informe técnico detallado y profesional.</li>
</ul>
</section>
<section id="alcances" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="alcances"><span class="header-section-number">2.3</span> Alcances</h2>
<p>El proyecto abarca el diseño, desarrollo y evaluación de tres módulos principales de aprendizaje profundo: predicción de demanda (con un horizonte de 30 días), clasificación de imágenes de conducción distractiva (identificando comportamientos específicos) y un sistema de recomendación de destinos. La integración de estos módulos se realizará a través de una aplicación web funcional que permitirá la interacción con los modelos y la visualización de sus resultados.</p>
</section>
<section id="limitaciones" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="limitaciones"><span class="header-section-number">2.4</span> Limitaciones</h2>
<p>Las limitaciones del proyecto incluyen la disponibilidad y calidad de los datos históricos, que pueden influir en la precisión de las predicciones y clasificaciones. Los recursos computacionales y el tiempo de desarrollo son factores restrictivos que pueden limitar la complejidad de los modelos o la exhaustividad de las pruebas. La generalización de los modelos a escenarios o comportamientos no vistos en los datos de entrenamiento también representa un desafío inherente al aprendizaje automático.</p>
<p>Para el despliegue de la herramienta web, debido a que se un proyecto académico, los recursos en la nube pueden ser limitados, lo que podría afectar la escalabilidad y disponibilidad del sistema. Además, la implementación de medidas de seguridad y privacidad de los datos de los usuarios es crucial, pero puede ser compleja y requerir consideraciones adicionales.</p>
</section>
</section>
<section id="metodología" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Metodología</h1>
<p>La metodología adoptada para el desarrollo de este sistema inteligente se basa en un enfoque modular y iterativo, siguiendo las mejores prácticas en el campo del aprendizaje automático y la ingeniería de software. Se usa git para el control de versiones y la colaboración en el desarrollo del código. Se usa CI/CD para asegurar la calidad del código y la integración continua de los módulos desarrollados.</p>
<section id="explicación-de-conceptos-clave" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="explicación-de-conceptos-clave"><span class="header-section-number">3.1</span> Explicación de Conceptos Clave</h2>
<ul>
<li><p>Aprendizaje Profundo (Deep Learning): Una rama del aprendizaje automático que utiliza redes neuronales artificiales con múltiples capas (profundas) para modelar abstracciones de alto nivel en los datos. Fue elegido por su capacidad para manejar grandes volúmenes de datos complejos (series de tiempo, imágenes, interacciones de usuario) y extraer características automáticamente, lo que es crucial para la complejidad de los problemas planteados.</p></li>
<li><p>Series de Tiempo: Secuencias de puntos de datos indexados (o listados) en orden de tiempo. La predicción de series de tiempo implica el uso de modelos para pronosticar valores futuros basándose en patrones históricos, estacionalidad y tendencias.</p></li>
<li><p>Redes Neuronales Convolucionales (CNNs): Un tipo de red neuronal profunda especialmente diseñada para procesar datos con una topología de cuadrícula, como imágenes. Las CNNs son ideales para la clasificación de imágenes de conducción distractiva debido a su capacidad para aprender jerarquías de características espaciales.</p></li>
<li><p>Sistemas de Recomendación: Algoritmos que sugieren elementos (destinos de viaje en este caso) a los usuarios basándose en sus preferencias pasadas y/o en el comportamiento de usuarios similares. Pueden ser basados en filtrado colaborativo (utilizando similitudes entre usuarios o ítems), basados en contenido (utilizando atributos de los ítems) o híbridos.</p></li>
</ul>
</section>
<section id="enfoque-general-del-proyecto" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="enfoque-general-del-proyecto"><span class="header-section-number">3.2</span> Enfoque General del Proyecto</h2>
<p>El proyecto se estructuró en torno a un enfoque modular, donde cada uno de los tres problemas principales (predicción de demanda, clasificación de conducción distractiva y recomendación de destinos) fue abordado como un módulo independiente con su propio ciclo de vida de desarrollo de modelo. Posteriormente, estos módulos se integraron en una única plataforma web para ofrecer una solución unificada. Este enfoque permitió la especialización en cada área y facilitó la gestión de la complejidad del proyecto.</p>
</section>
<section id="fases-del-proyecto" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="fases-del-proyecto"><span class="header-section-number">3.3</span> Fases del Proyecto</h2>
<p>Fase 1: Recopilación y Exploración de Datos:</p>
<ul>
<li><p>Identificación y acceso a las fuentes de datos para cada módulo (registros de transporte, imágenes de conductores, historial de viajes de usuarios).</p></li>
<li><p>Análisis Exploratorio de Datos (EDA) para comprender la estructura, calidad y patrones iniciales de los datos. Visualización de tendencias, distribución y anomalías.</p></li>
</ul>
<p>Fase 2: Preprocesamiento de Datos:</p>
<ul>
<li><p>Limpieza de Datos: Manejo de valores nulos, duplicados y atípicos.</p></li>
<li><p>Transformación: Normalización, estandarización, creación de características (feature engineering) específicas para cada tipo de dato (ej. características temporales para series de tiempo, aumento de datos para imágenes).</p></li>
<li><p>División de Datos: Separación en conjuntos de entrenamiento, validación y prueba para asegurar una evaluación imparcial del modelo.</p></li>
</ul>
<p>Fase 3: Desarrollo y Entrenamiento de Modelos:</p>
<ul>
<li><p>Diseño de Arquitecturas: Selección y diseño de las arquitecturas de redes neuronales profundas más adecuadas para cada módulo (ej. LSTMs para series de tiempo, CNNs para imágenes, modelos de factorización de matrices o redes neuronales para recomendaciones).</p></li>
<li><p>Implementación: Codificación de los modelos utilizando las librerías de aprendizaje profundo seleccionadas.</p></li>
<li><p>Entrenamiento: Proceso de ajuste de los pesos de los modelos utilizando los datos de entrenamiento, con monitoreo del rendimiento en el conjunto de validación.</p></li>
</ul>
<p>Fase 4: Evaluación y Optimización:</p>
<ul>
<li><p>Definición de Métricas: Selección de métricas de rendimiento apropiadas para cada tipo de problema (RMSE, MAE para predicción; Accuracy, F1-score, Precision, Recall para clasificación; Precision, Recall para recomendación).</p></li>
<li><p>Evaluación: Medición del rendimiento de los modelos en el conjunto de prueba, no visto durante el entrenamiento.</p></li>
<li><p>Optimización: Ajuste de hiperparámetros y refinamiento de las arquitecturas para mejorar el rendimiento.</p></li>
</ul>
<p>Fase 5: Integración y Desarrollo Web:</p>
<ul>
<li><p>Diseño de la Arquitectura Web: Planificación de la estructura de la aplicación web, incluyendo frontend, backend y la comunicación con los modelos.</p></li>
<li><p>Desarrollo de APIs: Creación de interfaces de programación de aplicaciones (APIs) para que la aplicación web pueda interactuar con los modelos entrenados.</p></li>
<li><p>Implementación de la Interfaz de Usuario: Desarrollo del frontend para visualizar resultados y permitir la interacción del usuario.</p></li>
</ul>
<p>Fase 6: Pruebas y Despliegue:</p>
<pre><code>Pruebas de Funcionalidad: Verificación de que todas las características del sistema integrado funcionan según lo esperado.

Pruebas de Rendimiento: Evaluación de la velocidad y eficiencia del sistema.

Despliegue: Preparación y lanzamiento del sistema en un entorno de producción. Se uso [Render](https://render.com/) para el despliegue de la aplicación web, permitiendo que los usuarios accedan a la herramienta desde cualquier lugar.</code></pre>
</section>
<section id="herramientas-y-tecnologías-utilizadas" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="herramientas-y-tecnologías-utilizadas"><span class="header-section-number">3.4</span> Herramientas y Tecnologías Utilizadas</h2>
<ul>
<li>Lenguaje de Programación: Python</li>
<li>Librerías de Aprendizaje Profundo: TensorFlow, Keras, Scikit-learn, PyTorch</li>
<li>Librerías de Manipulación de Datos: Pandas, NumPy</li>
<li>Librerías de Visualización: Matplotlib</li>
<li>Desarrollo Web (Backend): FastAPI</li>
<li>Desarrollo Web (Frontend): Javascript vanilla para la interactividad y Tailwind CSS para los estilos de la página web.</li>
<li>Entorno de Desarrollo: Jupyter Notebooks, VS Code</li>
<li>Control de Versiones: Git, GitHub</li>
</ul>
</section>
</section>
<section id="desarrollo-técnico-por-módulo" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Desarrollo Técnico por Módulo</h1>
<section id="módulo-1-predicción-de-demanda-de-transporte" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="módulo-1-predicción-de-demanda-de-transporte"><span class="header-section-number">4.1</span> Módulo 1: Predicción de Demanda de Transporte</h2>
<section id="descripción-del-problema" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="descripción-del-problema"><span class="header-section-number">4.1.1</span> Descripción del Problema</h3>
<p>El primer reto consiste en anticipar la demanda de transporte en rutas específicas durante los próximos 30 días. Esta predicción es esencial para garantizar que la empresa cuente con los recursos adecuados —vehículos, conductores y personal de apoyo— en los momentos y lugares donde se necesiten.</p>
<p>Para ello, se entrenará un modelo de series de tiempo sobre un conjunto de datos históricos reales proporcionado por el CRTM, el cual contiene información detallada de validaciones de transporte público (como número de pasajeros transportados por ruta y por fecha). Este módulo no solo busca predecir la evolución temporal de la demanda, sino también generar información útil para optimizar la planificación operativa, reducir tiempos de espera, minimizar recursos ociosos y mejorar la calidad del servicio.</p>
<p>La solución propuesta se fundamenta en técnicas de aprendizaje profundo especializadas en series temporales, tales como redes neuronales recurrentes (RNN), LSTM o modelos más modernos como Temporal Fusion Transformers. El objetivo es capturar patrones de estacionalidad, tendencias y variaciones anómalas que caracterizan el comportamiento de la demanda de transporte urbano en una ciudad como Madrid.</p>
<p>El conjunto de datos utilizado proviene del portal de datos abiertos del Consorcio Regional de Transportes de Madrid (CRTM). Este dataset, aunque sencillo en estructura, contiene información esencial para el análisis: fecha, modo de transporte (por ejemplo, autobús, metro o cercanías) y número de pasajeros transportados. A partir de estas variables, es posible construir una serie temporal robusta para cada modo de transporte, capturando patrones diarios, estacionales y tendencias a lo largo del tiempo. Esta base, al representar datos reales de demanda, resulta adecuada para entrenar modelos de predicción orientados a mejorar la planificación operativa.</p>
<div id="d1f71b6a" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># https://datos.crtm.es/documents/a7210254c4514a19a51b1617cfd61f75/about</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>ruta_al_archivo <span class="op">=</span> <span class="st">'./transporte_madrid.csv'</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(ruta_al_archivo)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Fecha'</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">'Fecha'</span>], dayfirst<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Crear columna `Month` como pide prepare_data</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df.rename(columns<span class="op">=</span>{<span class="st">'Fecha'</span>: <span class="st">'Month'</span>, <span class="st">'Valor'</span>: <span class="st">'#Passengers'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.groupby(<span class="st">'Month'</span>)[<span class="st">'#Passengers'</span>].<span class="bu">sum</span>().reset_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="dataset" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="dataset"><span class="header-section-number">4.1.2</span> Dataset</h3>
<section id="descripción-del-conjunto-de-datos" class="level4" data-number="4.1.2.1">
<h4 data-number="4.1.2.1" class="anchored" data-anchor-id="descripción-del-conjunto-de-datos"><span class="header-section-number">4.1.2.1</span> Descripción del Conjunto de Datos</h4>
<p>Para el desarrollo del modelo de predicción de demanda de transporte, se utilizó un conjunto de datos abierto proporcionado por el Consorcio Regional de Transportes de Madrid (CRTM). Este conjunto contiene información agregada sobre el uso del sistema de transporte público por día y modo de transporte, permitiendo construir series temporales por categoría.</p>
</section>
<section id="estructura-del-conjunto-de-datos" class="level4" data-number="4.1.2.2">
<h4 data-number="4.1.2.2" class="anchored" data-anchor-id="estructura-del-conjunto-de-datos"><span class="header-section-number">4.1.2.2</span> Estructura del conjunto de datos</h4>
<p>El archivo contiene tres variables principales:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 75%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Descripción</th>
<th>Tipo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Fecha</code></td>
<td>Fecha de la observación (formato AAAA-MM-DD)</td>
<td>Fecha</td>
</tr>
<tr class="even">
<td><code>Modo</code></td>
<td>Tipo de transporte utilizado (Ej: METRO, BUS, CERCANÍAS)</td>
<td>Categórica</td>
</tr>
<tr class="odd">
<td><code>Valor</code></td>
<td>Número de pasajeros registrados en esa fecha</td>
<td>Numérica</td>
</tr>
</tbody>
</table>
</section>
<section id="dimensiones-del-conjunto" class="level4" data-number="4.1.2.3">
<h4 data-number="4.1.2.3" class="anchored" data-anchor-id="dimensiones-del-conjunto"><span class="header-section-number">4.1.2.3</span> Dimensiones del conjunto</h4>
<ul>
<li>Cobertura temporal: Desde el 1 de enero de 2023 hasta el 29 de junio de 2025 (2.5 años).</li>
<li>Total de registros: 911 observaciones (dependiendo del número de modos y días disponibles).</li>
</ul>
</section>
<section id="ejemplo-de-registros" class="level4" data-number="4.1.2.4">
<h4 data-number="4.1.2.4" class="anchored" data-anchor-id="ejemplo-de-registros"><span class="header-section-number">4.1.2.4</span> Ejemplo de registros</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Fecha</th>
<th>Modo</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2023-02-15</td>
<td>BUS</td>
<td>945.218</td>
</tr>
<tr class="even">
<td>2023-02-15</td>
<td>METRO</td>
<td>1.221.504</td>
</tr>
<tr class="odd">
<td>2023-02-15</td>
<td>CERCANÍAS</td>
<td>287.564</td>
</tr>
</tbody>
</table>
</section>
<section id="consideraciones-para-el-modelado" class="level4" data-number="4.1.2.5">
<h4 data-number="4.1.2.5" class="anchored" data-anchor-id="consideraciones-para-el-modelado"><span class="header-section-number">4.1.2.5</span> Consideraciones para el modelado</h4>
<ul>
<li><p>Los datos están agregados a nivel diario por modo, sin segmentación por línea, estación o franja horaria.</p></li>
<li><p>No se cuenta con variables exógenas (clima, festivos, eventos), por lo que el enfoque será univariado por serie, aunque se puede modelar cada modo de transporte por separado o con modelos multivariados si se decide combinar las series.</p></li>
<li><p>Se observan patrones de estacionalidad semanal y anual, así como efectos de calendario (como menor demanda en fines de semana o festivos).</p></li>
</ul>
<div id="a390608c" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar y tomar los últimos 30 días</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>df_last_30 <span class="op">=</span> df.sort_values(<span class="st">'Month'</span>).tail(<span class="dv">90</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar la serie temporal</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">5</span>))</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>plt.plot(df_last_30[<span class="st">'Month'</span>], df_last_30[<span class="st">'#Passengers'</span>], marker<span class="op">=</span><span class="st">'o'</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="ss">f'Demanda diaria de los últimos 90 días'</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Fecha'</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Número de pasajeros'</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-3-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="preprocesamiento" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="preprocesamiento"><span class="header-section-number">4.1.3</span> Preprocesamiento</h3>
<section id="preparación-y-visualización-de-los-datos" class="level4" data-number="4.1.3.1">
<h4 data-number="4.1.3.1" class="anchored" data-anchor-id="preparación-y-visualización-de-los-datos"><span class="header-section-number">4.1.3.1</span> Preparación y Visualización de los Datos</h4>
<p>Antes de entrenar cualquier modelo de predicción, es fundamental realizar una limpieza, transformación y exploración inicial de los datos. Esto permite detectar patrones relevantes, anomalías y estacionalidades que influyen directamente en la demanda de transporte.</p>
<ol type="1">
<li>Carga y limpieza inicial</li>
</ol>
<ul>
<li>Se importó el conjunto de datos desde un archivo .csv con codificación UTF-8.</li>
<li>Se estandarizó el tipo de dato Fecha y se verificó la ausencia de valores nulos.</li>
<li>Se eliminaron registros con valores de pasajeros iguales a cero o inconsistencias por duplicación.</li>
</ul>
<ol start="2" type="1">
<li><p>Agregación por modo de transporte: Aunque los datos están segmentados por modo (BUS, METRO, CERCANÍAS), se decidió trabajar inicialmente con series separadas para cada uno, dada la naturaleza operativa distinta de cada sistema.</p></li>
<li><p>Visualización exploratoria Se graficó la demanda diaria de cada modo de transporte, lo que permitió identificar varios patrones:</p></li>
</ol>
<ul>
<li>Tendencia general: Incremento progresivo de la demanda.</li>
<li>Estacionalidad semanal: Caídas evidentes los fines de semana, especialmente domingos.</li>
<li>Estacionalidad anual: Reducción de demanda en los meses de verano y festivos largos.</li>
<li>Picos y valles anómalos: Algunos días con valores atípicos por eventos excepcionales o errores de medición.</li>
</ul>
<ol start="4" type="1">
<li>Transformaciones aplicadas</li>
</ol>
<ul>
<li>Se aplicó una transformación logarítmica opcional para estabilizar la varianza (en caso de que el modelo lo requiera).</li>
<li>Se realizaron pruebas de estacionariedad (Dickey-Fuller) para evaluar la necesidad de diferenciar la serie.</li>
</ul>
</section>
<section id="preparación-de-datos-y-creación-de-secuencias" class="level4" data-number="4.1.3.2">
<h4 data-number="4.1.3.2" class="anchored" data-anchor-id="preparación-de-datos-y-creación-de-secuencias"><span class="header-section-number">4.1.3.2</span> Preparación de datos y creación de secuencias</h4>
<p>Se diseñó una clase personalizada TimeSeriesDataset compatible con torch.utils.data.Dataset, encargada de generar automáticamente las secuencias de entrada (X) y las etiquetas de salida (y) necesarias para el entrenamiento del modelo. Cada muestra consiste en una secuencia de longitud fija (sequence_length) y su correspondiente valor siguiente como objetivo de predicción.</p>
<p>El código realiza lo siguiente:</p>
<ul>
<li>Convierte la serie escalada a FloatTensor.</li>
<li>Divide la serie en múltiples pares (secuencia, objetivo), usando una ventana deslizante.</li>
<li>Cada secuencia se entrega como un tensor de tamaño (sequence_length, 1).</li>
</ul>
</section>
<section id="división-temporal-del-conjunto-de-datos" class="level4" data-number="4.1.3.3">
<h4 data-number="4.1.3.3" class="anchored" data-anchor-id="división-temporal-del-conjunto-de-datos"><span class="header-section-number">4.1.3.3</span> División temporal del conjunto de datos</h4>
<p>Se utilizó una estrategia de validación temporal para dividir el conjunto de datos en entrenamiento y validación:</p>
<ul>
<li>Los datos anteriores al 1 de marzo de 2025 se usan para entrenamiento.</li>
<li>Los datos desde esa fecha se utilizan para validar la capacidad de generalización del modelo.</li>
</ul>
<p>Esta división respeta la naturaleza temporal de la serie y evita fugas de información del futuro hacia el pasado.</p>
</section>
<section id="escalamiento" class="level4" data-number="4.1.3.4">
<h4 data-number="4.1.3.4" class="anchored" data-anchor-id="escalamiento"><span class="header-section-number">4.1.3.4</span> Escalamiento</h4>
<p>Dado que las redes neuronales son sensibles a la escala de los datos, se aplicó una transformación MinMaxScaler() a los valores de pasajeros. Esta transformación se ajusta con los datos de entrenamiento y luego se aplica a los de validación.</p>
</section>
<section id="carga-eficiente-con-dataloader" class="level4" data-number="4.1.3.5">
<h4 data-number="4.1.3.5" class="anchored" data-anchor-id="carga-eficiente-con-dataloader"><span class="header-section-number">4.1.3.5</span> Carga eficiente con DataLoader</h4>
<p>Los datos se organizan y cargan mediante DataLoader, que permite:</p>
<ul>
<li>Entrenamiento en mini-lotes (batch_size=16) para mejorar la estabilidad del gradiente y la eficiencia computacional.</li>
<li>Mezcla aleatoria de las secuencias de entrenamiento (shuffle=True).</li>
<li>Validación con todos los datos de validación disponibles como un único lote.</li>
</ul>
</section>
<section id="codigo-para-la-preparación-de-datos" class="level4" data-number="4.1.3.6">
<h4 data-number="4.1.3.6" class="anchored" data-anchor-id="codigo-para-la-preparación-de-datos"><span class="header-section-number">4.1.3.6</span> Codigo para la preparación de datos</h4>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> TimeSeriesDataset(Dataset):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Custom Dataset class for time series data.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">    This class handles the creation of sequences and targets for time series prediction,</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co">    implementing the necessary methods for PyTorch's Dataset class.</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, data, sequence_length):</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>        <span class="co">"""</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co">        Initialize the dataset.</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co">        Parameters:</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co">        data (numpy.array): Input time series data</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co">        sequence_length (int): Length of input sequences</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co">        """</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.data <span class="op">=</span> torch.FloatTensor(data)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.sequence_length <span class="op">=</span> sequence_length</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__len__</span>(<span class="va">self</span>):</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>        <span class="co">"""Return the number of sequences in our dataset."""</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="bu">len</span>(<span class="va">self</span>.data) <span class="op">-</span> <span class="va">self</span>.sequence_length</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__getitem__</span>(<span class="va">self</span>, idx):</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>        <span class="co">"""</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="co">        Get a sequence and its corresponding target.</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="co">        Parameters:</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a><span class="co">        idx (int): Index of the sequence to retrieve</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a><span class="co">        Returns:</span></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="co">        tuple: (sequence, target) pair</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a><span class="co">        """</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>        sequence <span class="op">=</span> <span class="va">self</span>.data[idx:idx <span class="op">+</span> <span class="va">self</span>.sequence_length]</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>        target <span class="op">=</span> <span class="va">self</span>.data[idx <span class="op">+</span> <span class="va">self</span>.sequence_length]</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> sequence.view(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>), target</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> prepare_data(filename, split_date<span class="op">=</span><span class="st">'2025-01-01'</span>,</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>                sequence_length<span class="op">=</span><span class="dv">30</span>, batch_size<span class="op">=</span><span class="dv">32</span>):</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a><span class="co">    Prepare and split data into training and validation sets, creating DataLoader objects.</span></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters:</span></span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a><span class="co">    filename (str): Path to the CSV file</span></span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a><span class="co">    split_date (str): Date to split training and validation data</span></span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a><span class="co">    sequence_length (int): Length of input sequences</span></span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a><span class="co">    batch_size (int): Size of batches for training</span></span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a><span class="co">    tuple: Train DataLoader, validation DataLoader, scaler, original training data,</span></span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a><span class="co">           original validation data</span></span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Read the CSV file</span></span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.read_csv(filename)</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'Month'</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">'Month'</span>])</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Split data</span></span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a>    train_data <span class="op">=</span> df[df[<span class="st">'Month'</span>] <span class="op">&lt;</span> split_date]</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>    val_data <span class="op">=</span> df[df[<span class="st">'Month'</span>] <span class="op">&gt;=</span> split_date]</span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Scale the data</span></span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a>    scaler <span class="op">=</span> MinMaxScaler()</span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a>    train_scaled <span class="op">=</span> scaler.fit_transform(train_data[<span class="st">'#Passengers'</span>].values.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a>    val_scaled <span class="op">=</span> scaler.transform(val_data[<span class="st">'#Passengers'</span>].values.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create datasets</span></span>
<span id="cb4-67"><a href="#cb4-67" aria-hidden="true" tabindex="-1"></a>    train_dataset <span class="op">=</span> TimeSeriesDataset(train_scaled, sequence_length)</span>
<span id="cb4-68"><a href="#cb4-68" aria-hidden="true" tabindex="-1"></a>    val_dataset <span class="op">=</span> TimeSeriesDataset(val_scaled, sequence_length)</span>
<span id="cb4-69"><a href="#cb4-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-70"><a href="#cb4-70" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create dataloaders</span></span>
<span id="cb4-71"><a href="#cb4-71" aria-hidden="true" tabindex="-1"></a>    train_loader <span class="op">=</span> DataLoader(</span>
<span id="cb4-72"><a href="#cb4-72" aria-hidden="true" tabindex="-1"></a>        train_dataset,</span>
<span id="cb4-73"><a href="#cb4-73" aria-hidden="true" tabindex="-1"></a>        batch_size<span class="op">=</span>batch_size,</span>
<span id="cb4-74"><a href="#cb4-74" aria-hidden="true" tabindex="-1"></a>        shuffle<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb4-75"><a href="#cb4-75" aria-hidden="true" tabindex="-1"></a>        drop_last<span class="op">=</span><span class="va">False</span>  <span class="co"># Drop last incomplete batch</span></span>
<span id="cb4-76"><a href="#cb4-76" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-77"><a href="#cb4-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-78"><a href="#cb4-78" aria-hidden="true" tabindex="-1"></a>    val_loader <span class="op">=</span> DataLoader(</span>
<span id="cb4-79"><a href="#cb4-79" aria-hidden="true" tabindex="-1"></a>        val_dataset,</span>
<span id="cb4-80"><a href="#cb4-80" aria-hidden="true" tabindex="-1"></a>        batch_size<span class="op">=</span><span class="bu">len</span>(val_scaled)<span class="op">-</span>sequence_length,</span>
<span id="cb4-81"><a href="#cb4-81" aria-hidden="true" tabindex="-1"></a>        shuffle<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb4-82"><a href="#cb4-82" aria-hidden="true" tabindex="-1"></a>        drop_last<span class="op">=</span><span class="va">False</span></span>
<span id="cb4-83"><a href="#cb4-83" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-84"><a href="#cb4-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-85"><a href="#cb4-85" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> train_loader, val_loader, scaler, train_data, val_data, train_scaled, val_scaled</span>
<span id="cb4-86"><a href="#cb4-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-87"><a href="#cb4-87" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Prepare our data with the new functionality</span></span>
<span id="cb4-88"><a href="#cb4-88" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">1983</span>)</span>
<span id="cb4-89"><a href="#cb4-89" aria-hidden="true" tabindex="-1"></a>sequence_length <span class="op">=</span> <span class="dv">45</span></span>
<span id="cb4-90"><a href="#cb4-90" aria-hidden="true" tabindex="-1"></a>batch_size <span class="op">=</span> <span class="dv">16</span></span>
<span id="cb4-91"><a href="#cb4-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-92"><a href="#cb4-92" aria-hidden="true" tabindex="-1"></a>train_loader, val_loader, scaler, train_data, val_data, train_scaled, val_scaled <span class="op">=</span> prepare_data(</span>
<span id="cb4-93"><a href="#cb4-93" aria-hidden="true" tabindex="-1"></a>    filename <span class="op">=</span> <span class="st">'/content/ruta_location.csv'</span>,</span>
<span id="cb4-94"><a href="#cb4-94" aria-hidden="true" tabindex="-1"></a>    split_date<span class="op">=</span><span class="st">'2025-04-01'</span>,</span>
<span id="cb4-95"><a href="#cb4-95" aria-hidden="true" tabindex="-1"></a>    sequence_length<span class="op">=</span>sequence_length,</span>
<span id="cb4-96"><a href="#cb4-96" aria-hidden="true" tabindex="-1"></a>    batch_size<span class="op">=</span>batch_size</span>
<span id="cb4-97"><a href="#cb4-97" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-98"><a href="#cb4-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-99"><a href="#cb4-99" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> batch, (X,y) <span class="kw">in</span> <span class="bu">enumerate</span>(train_loader):</span>
<span id="cb4-100"><a href="#cb4-100" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="ss">f"El lote de inputs tiene dinmensiones </span><span class="sc">{</span>X<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-101"><a href="#cb4-101" aria-hidden="true" tabindex="-1"></a>  <span class="bu">print</span>(<span class="ss">f"El lote de targets tiene dimensiones </span><span class="sc">{</span>y<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-102"><a href="#cb4-102" aria-hidden="true" tabindex="-1"></a>  <span class="cf">break</span></span>
<span id="cb4-103"><a href="#cb4-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-104"><a href="#cb4-104" aria-hidden="true" tabindex="-1"></a>El lote de inputs tiene dinmensiones torch.Size([<span class="dv">16</span>, <span class="dv">45</span>, <span class="dv">1</span>])</span>
<span id="cb4-105"><a href="#cb4-105" aria-hidden="true" tabindex="-1"></a>El lote de targets tiene dimensiones torch.Size([<span class="dv">16</span>, <span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="diseño-de-modelo" class="level3" data-number="4.1.4">
<h3 data-number="4.1.4" class="anchored" data-anchor-id="diseño-de-modelo"><span class="header-section-number">4.1.4</span> Diseño de Modelo</h3>
<p>Para modelar la demanda de transporte en el tiempo, se optó por una arquitectura basada en redes neuronales recurrentes del tipo LSTM (Long Short-Term Memory), ampliamente utilizadas para modelar dependencias temporales en series de tiempo debido a su capacidad para retener información a largo plazo y mitigar el problema del desvanecimiento del gradiente.</p>
<section id="arquitectura-del-modelo" class="level4" data-number="4.1.4.1">
<h4 data-number="4.1.4.1" class="anchored" data-anchor-id="arquitectura-del-modelo"><span class="header-section-number">4.1.4.1</span> Arquitectura del Modelo</h4>
<p>El modelo se implementó mediante una clase personalizada passengersRNN utilizando PyTorch. Su estructura es la siguiente:</p>
<p>Capa LSTM: * Entrada univariada (input_size=1): representa el número de pasajeros por día. * Dos capas ocultas (num_layers=2) que permiten capturar patrones más complejos. * Cada capa oculta tiene 32 unidades (hidden_size=32). * Se incorpora dropout (dropout=0.2) como mecanismo de regularización para evitar sobreajuste. *La salida de la LSTM es una secuencia de vectores ocultos, pero solo se usa la salida del último paso temporal.</p>
<p>Capa fully-connected (lineal): Recibe el vector oculto final de la LSTM y lo transforma en un único valor escalar: la predicción del número de pasajeros para el siguiente día.</p>
</section>
<section id="mecanismo-de-inferencia-forward" class="level4" data-number="4.1.4.2">
<h4 data-number="4.1.4.2" class="anchored" data-anchor-id="mecanismo-de-inferencia-forward"><span class="header-section-number">4.1.4.2</span> Mecanismo de inferencia (forward)</h4>
<p>Durante la inferencia:</p>
<ul>
<li>Se inicializan los estados ocultos (h0) y de celda (c0) en cero.</li>
<li>Se pasa la secuencia de entrada por la LSTM.</li>
<li>Se extrae el estado oculto del último paso temporal (out[:, -1, :]).</li>
<li>Finalmente, se aplica la capa lineal para generar la predicción.</li>
</ul>
</section>
<section id="inicialización-del-modelo-y-modo-de-evaluación" class="level4" data-number="4.1.4.3">
<h4 data-number="4.1.4.3" class="anchored" data-anchor-id="inicialización-del-modelo-y-modo-de-evaluación"><span class="header-section-number">4.1.4.3</span> Inicialización del modelo y modo de evaluación</h4>
<p>El modelo se instancia con una semilla fija para garantizar la reproducibilidad. Posteriormente, se lleva a modo de evaluación (model.eval()), lo cual desactiva el dropout durante la inferencia:</p>
<p>En la siguiente sección se describirá el proceso de entrenamiento del modelo, incluyendo la función de pérdida utilizada, el optimizador, número de épocas y criterios de evaluación (como MAE, RMSE o MAPE).</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> passengersRNN(nn.Module):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>, input_size<span class="op">=</span><span class="dv">1</span>, hidden_size<span class="op">=</span><span class="dv">32</span>, num_layers<span class="op">=</span><span class="dv">2</span>, dropout<span class="op">=</span><span class="fl">0.2</span>):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>(passengersRNN, <span class="va">self</span>).<span class="fu">__init__</span>()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.hidden_size <span class="op">=</span> hidden_size</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.num_layers <span class="op">=</span> num_layers</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.lstm <span class="op">=</span> nn.LSTM(</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>            input_size<span class="op">=</span>input_size,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>            hidden_size<span class="op">=</span>hidden_size,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>            num_layers<span class="op">=</span>num_layers,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>            batch_first<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>            dropout<span class="op">=</span>dropout  <span class="co"># Add dropout for regularization</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc <span class="op">=</span> nn.Linear(hidden_size, <span class="dv">1</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        batch_size <span class="op">=</span> x.size(<span class="dv">0</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        h0 <span class="op">=</span> torch.zeros(<span class="va">self</span>.num_layers, batch_size, <span class="va">self</span>.hidden_size).to(x.device)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>        c0 <span class="op">=</span> torch.zeros(<span class="va">self</span>.num_layers, batch_size, <span class="va">self</span>.hidden_size).to(x.device)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>        out, h <span class="op">=</span> <span class="va">self</span>.lstm(x, (h0, c0))</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>        out <span class="op">=</span> <span class="va">self</span>.fc(out[:, <span class="op">-</span><span class="dv">1</span>, :])</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> out</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize our model</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">1983</span>)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> passengersRNN().to(device)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>model.<span class="bu">eval</span>() <span class="co"># Cancela el dropout cuando invocamos el modelo</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> torch.no_grad():</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  y_pred <span class="op">=</span> model(X.to(device))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="entrenamiento-del-modelo" class="level3" data-number="4.1.5">
<h3 data-number="4.1.5" class="anchored" data-anchor-id="entrenamiento-del-modelo"><span class="header-section-number">4.1.5</span> Entrenamiento del modelo</h3>
<p>Una vez definida la arquitectura, se procedió al entrenamiento del modelo LSTM utilizando un ciclo de aprendizaje supervisado. Para ello, se implementó una función personalizada train_model que gestiona tanto la fase de entrenamiento como la de validación en cada época, haciendo uso eficiente de los objetos DataLoader.</p>
<section id="configuración-de-entrenamiento" class="level4" data-number="4.1.5.1">
<h4 data-number="4.1.5.1" class="anchored" data-anchor-id="configuración-de-entrenamiento"><span class="header-section-number">4.1.5.1</span> Configuración de entrenamiento</h4>
<ul>
<li>Función de pérdida: Se empleó el error cuadrático medio (MSE), una métrica estándar para problemas de regresión, especialmente útil cuando se penalizan errores grandes de forma cuadrática.</li>
<li>Optimizador: Se utilizó el algoritmo Adam, conocido por su eficiencia computacional y capacidad de adaptación del learning rate durante el entrenamiento.</li>
<li>Tasa de aprendizaje: lr=0.001, ajustada para favorecer una convergencia estable.</li>
<li>Épocas: El modelo fue entrenado por 150 iteraciones completas sobre el conjunto de entrenamiento.</li>
</ul>
</section>
<section id="proceso-de-entrenamiento" class="level4" data-number="4.1.5.2">
<h4 data-number="4.1.5.2" class="anchored" data-anchor-id="proceso-de-entrenamiento"><span class="header-section-number">4.1.5.2</span> Proceso de entrenamiento</h4>
<p>En cada época del entrenamiento se ejecutan dos fases: * Fase de entrenamiento (model.train()): * El modelo se entrena por mini-lotes usando train_loader. * Se calcula la pérdida por lote. * Se hace backpropagation (loss.backward()), se actualizan los pesos (optimizer.step()), y se reinician los gradientes.</p>
<ul>
<li>Fase de validación (model.eval()):
<ul>
<li>El modelo se evalúa con el conjunto de validación completo, sin actualizar pesos y con dropout desactivado.</li>
<li>Se calcula la pérdida de validación para monitorear la capacidad de generalización.</li>
</ul></li>
</ul>
</section>
<section id="monitoreo-del-rendimiento" class="level4" data-number="4.1.5.3">
<h4 data-number="4.1.5.3" class="anchored" data-anchor-id="monitoreo-del-rendimiento"><span class="header-section-number">4.1.5.3</span> Monitoreo del rendimiento</h4>
<p>Se almacenaron las pérdidas promedio por época para entrenamiento y validación. Esto permitió visualizar la evolución del aprendizaje y detectar posibles señales de sobreajuste o subajuste.</p>
<p>La siguiente figura muestra la evolución de la pérdida (error cuadrático medio) durante las 150 épocas del entrenamiento para los conjuntos de entrenamiento y validación:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./modelo1_perdida.png" class="img-fluid figure-img"></p>
<figcaption>evolución de la pérdida</figcaption>
</figure>
</div>
<ul>
<li><p>Convergencia rápida: En las primeras 20 épocas se observa una reducción abrupta en ambas curvas de pérdida, lo que indica que el modelo aprendió rápidamente patrones generales de la serie.</p></li>
<li><p>Estabilización: A partir de la época 40, las curvas tienden a estabilizarse, señal de que el modelo ha llegado a una zona de mínimo estable de la función de pérdida.</p></li>
<li><p>Generalización adecuada: La curva de validación se mantiene por debajo de la de entrenamiento, lo cual sugiere una buena capacidad de generalización y ausencia de sobreajuste. Esto se refuerza por la baja varianza entre épocas en la curva de validación.</p></li>
</ul>
</section>
</section>
<section id="evaluación-y-resultados" class="level3" data-number="4.1.6">
<h3 data-number="4.1.6" class="anchored" data-anchor-id="evaluación-y-resultados"><span class="header-section-number">4.1.6</span> Evaluación y Resultados</h3>
<section id="obteniendo-predicciones-del-modelo" class="level4" data-number="4.1.6.1">
<h4 data-number="4.1.6.1" class="anchored" data-anchor-id="obteniendo-predicciones-del-modelo"><span class="header-section-number">4.1.6.1</span> Obteniendo predicciones del modelo</h4>
<p>Una vez entrenado el modelo, se procedió a realizar predicciones sobre el horizonte de validación con el objetivo de evaluar su desempeño en un entorno no visto durante el entrenamiento.</p>
<ol type="1">
<li>Predicción paso a paso (modo autorregresivo) Se implementó una función predict_sequence que genera predicciones de manera autoregresiva, es decir, utilizando la propia salida del modelo como nueva entrada para el siguiente paso. Este enfoque permite proyectar la serie hacia el futuro, partiendo de la última secuencia disponible del conjunto de entrenamiento.</li>
</ol>
<ul>
<li>Se toma la última ventana temporal de tamaño sequence_length.</li>
<li>Se hacen predicciones iterativas para tantos pasos como se desee (en este caso, igual al tamaño del conjunto de validación).</li>
<li>Tras cada predicción, se actualiza la secuencia incluyendo el valor recién estimado.</li>
<li>Finalmente, las predicciones se reescalan a la escala original mediante la inversa de MinMaxScaler.</li>
</ul>
<ol start="2" type="1">
<li>Cálculo de métricas de evaluación Para cuantificar la precisión del modelo, se calcularon las siguientes métricas sobre los datos de validación reales vs.&nbsp;predichos:</li>
</ol>
<ul>
<li>MSE (Error Cuadrático Medio)</li>
<li>RMSE (Raíz del Error Cuadrático Medio)</li>
<li>MAE (Error Absoluto Medio)</li>
<li>MAPE (Error Porcentual Absoluto Medio)</li>
</ul>
</section>
<section id="gráficas-de-predicción-vs.-demanda-real" class="level4" data-number="4.1.6.2">
<h4 data-number="4.1.6.2" class="anchored" data-anchor-id="gráficas-de-predicción-vs.-demanda-real"><span class="header-section-number">4.1.6.2</span> Gráficas de predicción vs.&nbsp;demanda real</h4>
<p>Finalizado el entrenamiento, se generaron predicciones sobre el conjunto de validación utilizando el enfoque autorregresivo. Esto implicó tomar la última secuencia de entrenamiento y, en cada paso, utilizar la predicción previa como entrada para generar la siguiente.</p>
<p>Predicciones paso a paso El modelo fue capaz de predecir la demanda diaria durante el periodo comprendido entre marzo y julio de 2025. El proceso incluyó la inversión del escalado aplicado previamente, con el fin de comparar las predicciones en la misma escala que los datos reales.</p>
<p>Visualización: valores reales vs.&nbsp;predicciones La siguiente figura muestra la comparación entre los valores reales de número de pasajeros y las predicciones generadas por el modelo:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./modelo1_predicciones.png" class="img-fluid figure-img"></p>
<figcaption>Predicciones del modelo</figcaption>
</figure>
</div>
</section>
<section id="análisis-de-la-estacionalidad-y-tendencias" class="level4" data-number="4.1.6.3">
<h4 data-number="4.1.6.3" class="anchored" data-anchor-id="análisis-de-la-estacionalidad-y-tendencias"><span class="header-section-number">4.1.6.3</span> Análisis de la estacionalidad y tendencias</h4>
<ul>
<li><p>El modelo logra capturar correctamente la estacionalidad semanal, con ciclos que reflejan la disminución de pasajeros los fines de semana.</p></li>
<li><p>Sin embargo, tiende a subestimar los picos de demanda durante los días laborales, manteniéndose en niveles más estables.</p></li>
<li><p>Esto puede deberse a la naturaleza conservadora del modelo o a una limitación de información contextual (por ejemplo, feriados o eventos especiales no incluidos como variables exógenas).</p></li>
</ul>
</section>
<section id="métricas-de-desempeño" class="level4" data-number="4.1.6.4">
<h4 data-number="4.1.6.4" class="anchored" data-anchor-id="métricas-de-desempeño"><span class="header-section-number">4.1.6.4</span> Métricas de desempeño</h4>
<p>A continuación se resumen las métricas de error sobre el conjunto de validación:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Métrica</th>
<th>Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MSE</td>
<td>726063597870.29</td>
</tr>
<tr class="even">
<td>RMSE</td>
<td>852093.66</td>
</tr>
<tr class="odd">
<td>MAE</td>
<td>589533.53</td>
</tr>
<tr class="even">
<td>MAPE</td>
<td>14.54</td>
</tr>
</tbody>
</table>
<p>Estas métricas indican un error medio absoluto cercano a los 589 mil pasajeros por día, lo cual representa un 14.5% de desviación media relativa respecto a los valores reales. Si bien el modelo generaliza bien la forma de la serie, aún presenta limitaciones para captar la magnitud exacta de los picos más altos, lo cual podría mejorarse con modelos más sofisticados o variables adicionales.</p>
</section>
<section id="conclusiones-del-módulo-1" class="level4" data-number="4.1.6.5">
<h4 data-number="4.1.6.5" class="anchored" data-anchor-id="conclusiones-del-módulo-1"><span class="header-section-number">4.1.6.5</span> Conclusiones del Módulo 1</h4>
<p>El presente módulo logró desarrollar un modelo de predicción basado en redes neuronales LSTM para anticipar la demanda diaria de pasajeros en el sistema de transporte público. A partir de una serie temporal univariada, se construyó un enfoque autorregresivo que permitió proyectar la demanda futura con un horizonte de 30 días.</p>
<p>Los principales logros y hallazgos del módulo fueron:</p>
<p>Se implementó un pipeline robusto de preprocesamiento, escalamiento, estructuración de secuencias y entrenamiento eficiente mediante DataLoader.</p>
<p>El modelo logró capturar patrones de estacionalidad semanal y tendencia general, ajustándose de forma razonable a la estructura temporal de la serie.</p>
<p>Las métricas de desempeño obtenidas —RMSE de 852.093, MAE de 589.533 y MAPE de 14,5%— evidencian un nivel de error aceptable para tareas de planificación operativa, aunque con margen de mejora.</p>
<p>Se observó una tendencia del modelo a subestimar los valores máximos de demanda, lo cual sugiere que futuras versiones podrían beneficiarse del uso de modelos multivariados, incorporación de variables externas (eventos, clima, calendario), o arquitecturas más avanzadas (como Transformers o híbridos LSTM-CNN).</p>
<p>En síntesis, este módulo demuestra el potencial de los modelos de aprendizaje profundo para apoyar la planificación estratégica de recursos en una empresa de transporte, al anticipar comportamientos de la demanda que permiten tomar decisiones informadas y oportunas.</p>
</section>
</section>
</section>
<section id="módulo-2-clasificación-de-conducción-distractiva" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="módulo-2-clasificación-de-conducción-distractiva"><span class="header-section-number">4.2</span> Módulo 2: Clasificación de Conducción Distractiva</h2>
<section id="descripción-del-problema-1" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="descripción-del-problema-1"><span class="header-section-number">4.2.1</span> Descripción del problema</h3>
<p>Este módulo tiene como objetivo detectar comportamientos distractores en los conductores a partir de imágenes, con el fin de mejorar la seguridad vial. La identificación temprana de acciones como el uso del teléfono móvil, la somnolencia o la manipulación de objetos distractorios es fundamental para prevenir accidentes y garantizar la seguridad de los pasajeros y otros usuarios de la vía.</p>
</section>
<section id="dataset-1" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="dataset-1"><span class="header-section-number">4.2.2</span> Dataset</h3>
<p><img src="modelo2_dataset1.png" class="img-fluid" alt="modelo2_dataset1"> <img src="modelo2_dataset2.png" class="img-fluid" alt="modelo2_dataset2"></p>
<p>El conjunto de datos de imágenes consiste en una colección de fotografías de conductores, categorizadas en diferentes clases de comportamiento. Las imágenes provienen de un dataset publico en kaggle llamado <a href="https://www.kaggle.com/datasets/arafatsahinafridi/multi-class-driver-behavior-image-dataset/data?authuser=1">Multi-Class Driver Behavior Image Dataset</a>.</p>
<p>Este dataset fue recopilado en Ashulia, Dhaka (Bangladesh) en octubre de 2024, y contiene imágenes reales capturadas dentro de automóviles particulares y autobuses públicos en condiciones normales de conducción. Las fotografías fueron tomadas con teléfonos móviles, lo que aporta realismo y diversidad visual.</p>
<p>El objetivo del dataset es facilitar el desarrollo de sistemas de monitoreo en tiempo real que detecten comportamientos de conducción distraída, un problema crítico a nivel mundial.</p>
<p>Contiene imágenes clasificadas en cinco tipos de comportamiento del conductor:</p>
<ol type="1">
<li><p><strong>Conducción Segura</strong>: El conductor está atento, con ambas manos al volante o una en el volante y otra en la palanca.</p></li>
<li><p><strong>Girando</strong>: El conductor gira la cabeza o el cuerpo para cambiar de dirección.</p></li>
<li><p><strong>Escribiendo en el Teléfono</strong>: Uso activo del teléfono para mensajes u otras interacciones.</p></li>
<li><p><strong>Hablando por Teléfono</strong>: El conductor sostiene el teléfono en la oreja o habla mientras maneja.</p></li>
<li><p><strong>Otros</strong>: Acciones peligrosas como beber, dormir, o conversar con pasajeros traseros.</p></li>
</ol>
<p>Las imágenes varían en iluminación, tipo de vehículo y no están procesadas ni etiquetadas, lo cual permite flexibilidad para su uso en aplicaciones de aprendizaje automático.</p>
</section>
<section id="preprocesamiento-1" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="preprocesamiento-1"><span class="header-section-number">4.2.3</span> Preprocesamiento:</h3>
<p>El preprocesamiento de los datos se hizo principalmente con ImageDataGenerator de Keras, siguiendo estos pasos:</p>
<ol type="1">
<li><p><strong>Reescalado de imágenes</strong>: Todas las imágenes se normalizan dividiendo los valores de los píxeles por 255 (rescale=1./255), convirtiendo los valores de 0-255 a 0-1.</p></li>
<li><p><strong>Redimensionamiento</strong>: Las imágenes se redimensionan a un tamaño fijo (img_size), por ejemplo (224, 224) o (256, 256), según el modelo y la etapa.</p></li>
<li><p><strong>División en entrenamiento y validación</strong>: Se utiliza el parámetro <code>validation_split=0.2</code> para separar automáticamente el 20% de los datos para validación.</p></li>
<li><p><strong>Aumento de datos (Data Augmentation)</strong>: Para el entrenamiento, se aplican transformaciones aleatorias como:</p></li>
</ol>
<ul>
<li>Rotaciones (rotation_range)</li>
<li>Desplazamientos horizontales y verticales (width_shift_range, height_shift_range)</li>
<li>Shear, zoom y volteo horizontal (shear_range, zoom_range, horizontal_flip) Esto ayuda a que el modelo generalice mejor y no se sobreentrene.</li>
</ul>
<ol start="5" type="1">
<li><p><strong>Conversión a escala de grises</strong>: En los modelos CNN personalizados, se usa <code>color_mode='grayscale'</code> para convertir las imágenes a una sola canal, ya que el color no es relevante para la tarea.</p></li>
<li><p><strong>Carga por lotes y codificación de etiquetas</strong>: <code>flow_from_directory</code> carga las imágenes en lotes (batch_size) y asigna etiquetas en formato one-hot (class_mode=‘categorical’).</p></li>
<li><p><strong>Balanceo de clases</strong>: Se calcula <code>class_weight</code> para compensar posibles desbalances en la cantidad de imágenes por clase, mejorando el aprendizaje en clases minoritarias.</p></li>
</ol>
</section>
<section id="diseño-de-modelo-1" class="level3" data-number="4.2.4">
<h3 data-number="4.2.4" class="anchored" data-anchor-id="diseño-de-modelo-1"><span class="header-section-number">4.2.4</span> Diseño de Modelo</h3>
<p>Se implementó una red neuronal convolucional (CNN) secuencial compuesta por varias capas Conv2D, MaxPooling2D, BatchNormalization, Dropout y Dense. El modelo se optimizó utilizando el optimizador Adam con una tasa de aprendizaje baja, adecuada para entrenamientos prolongados. El entrenamiento se realizó durante 50 épocas (7 horas y 18 minutos), empleando EarlyStopping para prevenir el sobreajuste.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> Sequential([</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    Conv2D(<span class="dv">32</span>, (<span class="dv">3</span>,<span class="dv">3</span>), activation<span class="op">=</span><span class="st">'relu'</span>, input_shape<span class="op">=</span>img_size <span class="op">+</span> (<span class="dv">1</span>,)),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    BatchNormalization(),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    MaxPooling2D(<span class="dv">2</span>,<span class="dv">2</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    Conv2D(<span class="dv">64</span>, (<span class="dv">3</span>,<span class="dv">3</span>), activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    BatchNormalization(),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    MaxPooling2D(<span class="dv">2</span>,<span class="dv">2</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    Conv2D(<span class="dv">128</span>, (<span class="dv">3</span>,<span class="dv">3</span>), activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    BatchNormalization(),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    MaxPooling2D(<span class="dv">2</span>,<span class="dv">2</span>),</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    Flatten(),</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    Dense(<span class="dv">256</span>, activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    Dropout(<span class="fl">0.5</span>),</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    Dense(num_classes, activation<span class="op">=</span><span class="st">'softmax'</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="evaluación" class="level3" data-number="4.2.5">
<h3 data-number="4.2.5" class="anchored" data-anchor-id="evaluación"><span class="header-section-number">4.2.5</span> Evaluación</h3>
<section id="perdida-del-modelo" class="level4" data-number="4.2.5.1">
<h4 data-number="4.2.5.1" class="anchored" data-anchor-id="perdida-del-modelo"><span class="header-section-number">4.2.5.1</span> Perdida del modelo</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="modelo2_perdida.png" class="img-fluid figure-img"></p>
<figcaption>modelo2_perdida.png</figcaption>
</figure>
</div>
<p>La gráfica muestra la evolución de la pérdida durante el entrenamiento del modelo. Se observa una disminución constante de la pérdida tanto en el conjunto de entrenamiento como en el de validación, lo que indica que el modelo está aprendiendo correctamente y no presenta signos de sobreajuste.</p>
</section>
<section id="matriz-de-confusión" class="level4" data-number="4.2.5.2">
<h4 data-number="4.2.5.2" class="anchored" data-anchor-id="matriz-de-confusión"><span class="header-section-number">4.2.5.2</span> Matriz de Confusión</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="matrixconfusion_modelo2.png" class="img-fluid figure-img" width="800"></p>
<figcaption>Matrix de Confusión</figcaption>
</figure>
</div>
<ul>
<li>El mayor número de errores se presenta en la clase “other_activities”, debido a la similitud visual con otras clases (posición de cabeza, manos, detalles sutiles en el rostro).</li>
</ul>
</section>
<section id="reporte-de-clasificación" class="level4" data-number="4.2.5.3">
<h4 data-number="4.2.5.3" class="anchored" data-anchor-id="reporte-de-clasificación"><span class="header-section-number">4.2.5.3</span> Reporte de clasificación:</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Clase</th>
<th>Precisión</th>
<th>Recall</th>
<th>F1-score</th>
<th>Soporte</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>other_activities</td>
<td>0.63</td>
<td>0.80</td>
<td>0.71</td>
<td>1184</td>
</tr>
<tr class="even">
<td>safe_driving</td>
<td>0.92</td>
<td>0.77</td>
<td>0.84</td>
<td>1679</td>
</tr>
<tr class="odd">
<td>talking_phone</td>
<td>0.88</td>
<td>0.81</td>
<td>0.84</td>
<td>1513</td>
</tr>
<tr class="even">
<td>texting_phone</td>
<td>0.86</td>
<td>0.94</td>
<td>0.90</td>
<td>1561</td>
</tr>
<tr class="odd">
<td>turning</td>
<td>0.92</td>
<td>0.89</td>
<td>0.90</td>
<td>1339</td>
</tr>
<tr class="even">
<td>Promedio</td>
<td>0.84</td>
<td>0.84</td>
<td>0.84</td>
<td>7276</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="resultados" class="level3" data-number="4.2.6">
<h3 data-number="4.2.6" class="anchored" data-anchor-id="resultados"><span class="header-section-number">4.2.6</span> Resultados</h3>
<ul>
<li><p>El modelo aprendió de manera correcta después de 50 épocas y más de 7 horas de entrenamiento, alcanzando una precisión del 84% en la validación.</p></li>
<li><p>El mayor desafío fue la distinción de la clase “other_activities”, ya que muchas poses y detalles visuales son muy similares entre clases, incluso para un humano.</p></li>
<li><p>Se recomienda siempre revisar visualmente las predicciones del modelo, especialmente en casos ambiguos.</p></li>
</ul>
<section id="posibles-mejoras" class="level4" data-number="4.2.6.1">
<h4 data-number="4.2.6.1" class="anchored" data-anchor-id="posibles-mejoras"><span class="header-section-number">4.2.6.1</span> Posibles mejoras:</h4>
<ul>
<li><p>Ampliar el dataset con más imágenes reales (no artificiales).</p></li>
<li><p>Aumentar la capacidad de cómputo para reducir el tiempo de entrenamiento.</p></li>
<li><p>Experimentar con imágenes en RGB vs.&nbsp;escala de grises, aunque los colores no parecen ser determinantes para la tarea.</p></li>
<li><p>Analizar si una arquitectura más profunda o técnicas de atención pueden mejorar la discriminación entre clases visualmente similares.</p></li>
</ul>
</section>
</section>
</section>
<section id="módulo-3-recomendación-de-destinos-de-viaje" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="módulo-3-recomendación-de-destinos-de-viaje"><span class="header-section-number">4.3</span> Módulo 3: Recomendación de Destinos de Viaje</h2>
<section id="descripción-del-problema-2" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="descripción-del-problema-2"><span class="header-section-number">4.3.1</span> Descripción del Problema</h3>
<p>El objetivo de este módulo es desarrollar un sistema que sugiera destinos de viaje personalizados a los usuarios de la empresa, basándose en su historial de viajes y preferencias. Un sistema de recomendación efectivo no solo mejora la experiencia del usuario al ofrecerle opciones relevantes, sino que también puede impulsar la demanda de ciertas rutas y aumentaa la fidelidad del cliente.</p>
</section>
<section id="dataset-2" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="dataset-2"><span class="header-section-number">4.3.2</span> Dataset</h3>
<p>Se uso un dataset publico en kaggle llamado <a href="https://www.kaggle.com/datasets/amanmehra23/travel-recommendation-dataset?authuser=1">Travel Recommendation Dataset</a>. Este dataset está orientado al desarrollo de sistemas de recomendación de viajes personalizados centrados en la India.</p>
<p>El dataset se compone de cuatro archivos CSV principales:</p>
<ol type="1">
<li><p><strong>Destinos</strong>: Información detallada sobre lugares turísticos en India (tipo de destino, popularidad, mejor época para visitar, etc.).</p></li>
<li><p><strong>Usuarios</strong>: Perfiles con datos demográficos y preferencias de viaje, incluyendo composición del grupo (adultos, niños) y diversidad de género.</p></li>
<li><p><strong>Reseñas</strong>: Reseñas: Opiniones y valoraciones de usuarios sobre los destinos visitados, útiles para análisis de satisfacción y sentimientos.</p></li>
<li><p><strong>Historial de Usuarios</strong>: Registros de destinos previamente visitados y calificaciones otorgadas.</p></li>
</ol>
</section>
<section id="preprocesamiento-2" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="preprocesamiento-2"><span class="header-section-number">4.3.3</span> Preprocesamiento</h3>
<p>El preprocesamiento de los datos se realizó en varios etapas clave:</p>
<ol type="1">
<li><p><strong>Carga de archivos CSV</strong>: Todos los archivos se leyeron con <code>pandas.read_csv</code> y se concatenaron en un único DataFrame.</p></li>
<li><p><strong>Visualización inicial</strong>: Se observo información general, se buscaron valores nulos y se identificaron tipos de datos, adicionalmente se graficaron las distribuciones de variables numéricas y categóricas usando <code>matplotlib</code>.</p></li>
</ol>
<div id="abf54e08" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> glob</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> MinMaxScaler</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. CARGA, VISUALIZACIÓN Y LIMPIEZA DEL DATASET</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>carpeta <span class="op">=</span> <span class="vs">r'</span><span class="dv">.</span><span class="vs">/recomendaciones'</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>archivos_csv <span class="op">=</span> glob.glob(os.path.join(carpeta, <span class="st">'*.csv'</span>))</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="kw">not</span> archivos_csv:</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">FileNotFoundError</span>(<span class="ss">f'No se encontraron archivos CSV en la carpeta: </span><span class="sc">{</span>carpeta<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Se encontraron </span><span class="sc">{</span><span class="bu">len</span>(archivos_csv)<span class="sc">}</span><span class="ss"> archivos CSV.'</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Cargar y concatenar los archivos CSV</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    dfs <span class="op">=</span> [pd.read_csv(archivo) <span class="cf">for</span> archivo <span class="kw">in</span> archivos_csv]</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.concat(dfs, ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> <span class="pp">Exception</span> <span class="im">as</span> e:</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">raise</span> <span class="pp">RuntimeError</span>(<span class="ss">f'Error al cargar los archivos CSV: </span><span class="sc">{</span>e<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualización de variables numéricas y categóricas (opcional)</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>num_cols <span class="op">=</span> df.select_dtypes(include<span class="op">=</span>[<span class="st">'float64'</span>, <span class="st">'int64'</span>]).columns</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>cat_cols <span class="op">=</span> df.select_dtypes(include<span class="op">=</span>[<span class="st">'object'</span>]).columns</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>MOSTRAR_GRAFICOS<span class="op">=</span><span class="va">True</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> MOSTRAR_GRAFICOS:</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> num_cols:</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>        plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>,<span class="dv">4</span>))</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>        df[col].hist(bins<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>        plt.title(<span class="ss">f'Distribución de </span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>        plt.xlabel(col, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>        plt.ylabel(<span class="st">'Frecuencia'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>        plt.tight_layout()</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>        plt.show()</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> cat_cols:</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>        plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>,<span class="dv">4</span>))</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>        df[col].value_counts().head(<span class="dv">10</span>).plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>        plt.title(<span class="ss">f'Frecuencia de </span><span class="sc">{</span>col<span class="sc">}</span><span class="ss">'</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>        plt.xlabel(col, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>        plt.ylabel(<span class="st">'Frecuencia'</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>        plt.tight_layout()</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>        plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Se encontraron 4 archivos CSV.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-8.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-9.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-10.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-11.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-12.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-13.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-14.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-15.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-16.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-17.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-18.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-19.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li><strong>Limpieza de valores nulos</strong></li>
</ol>
<ul>
<li><p>Para columnas numéricas, los valores nulos se rellenaron con la mediana de cada columna.</p></li>
<li><p>Para columnas categóricas, los valores nulos se rellenaron con la moda (valor más frecuente) o con ‘Desconocido’ si la moda no estaba disponible.</p></li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Limpieza básica: rellenar NaN</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> num_cols:</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    n_null <span class="op">=</span> df[col].isnull().<span class="bu">sum</span>()</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> df[col].fillna(df[col].median())</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> cat_cols:</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    n_null <span class="op">=</span> df[col].isnull().<span class="bu">sum</span>()</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> df[col].fillna(df[col].mode()[<span class="dv">0</span>] <span class="cf">if</span> <span class="kw">not</span> df[col].mode().empty <span class="cf">else</span> <span class="st">'Desconocido'</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalización de variables numéricas (excluyendo IDs si existen)</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>cols_to_normalize <span class="op">=</span> [col <span class="cf">for</span> col <span class="kw">in</span> num_cols <span class="cf">if</span> <span class="kw">not</span> col.lower().endswith(<span class="st">'id'</span>)]</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> MinMaxScaler()</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>df[cols_to_normalize] <span class="op">=</span> scaler.fit_transform(df[cols_to_normalize])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="4" type="1">
<li><p><strong>Normalización de variables numéricas</strong>: Se normalizaron las columnas numéricas (excepto aquellas cuyo nombre termina en ‘id’) usando MinMaxScaler de scikit-learn, escalando sus valores entre 0 y 1.</p></li>
<li><p><strong>Simulación de datos adicionales</strong>: Para aumentar la diversidad y cantidad de datos, se generaron registros simulados de usuarios y destinos, basados en las distribuciones reales de los datos originales. Estos datos simulados se concatenaron al DataFrame original.</p></li>
<li><p><strong>Construcción de features de texto</strong>: Creación de una columna features combinando nombre, tipo, estado, preferencias, época y popularidad, todo normalizado y en minúsculas.</p></li>
</ol>
</section>
<section id="diseño-de-modelo-2" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="diseño-de-modelo-2"><span class="header-section-number">4.3.4</span> Diseño de Modelo</h3>
<p>El diseño del modelo sigue un enfoque híbrido, combinando técnicas de filtrado colaborativo y basado en contenido.</p>
<ol type="1">
<li><p><strong>1. Matriz de Interacción Usuario-Destino</strong>: Se creó una matriz donde las filas son usuarios y las columnas son destinos, y el valor es el rating o experiencia (<code>ExperienceRating</code> o <code>Rating</code>) que el usuario dio al destino. Esto permite medir la similitud entre usuarios usando la función <code>cosine_similarity</code>.</p></li>
<li><p><strong>Modelo Basado en Contenido</strong>: Se generó una columna <code>features</code> para cada destino, combinando y normalizando información relevante (nombre, tipo, estado, preferencias, época, popularidad, etc.). Luego, se vectorizó esta columna usando <code>CountVectorizer</code> y se calculó la similitud de coseno entre destinos, obteniendo una matriz de similitud de destinos.</p></li>
</ol>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'features'</span>] <span class="op">=</span> (</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'Name'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'Type'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'State'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'Preferences'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'BestTimeToVisit'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'Popularity'</span>].astype(<span class="bu">str</span>) <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'State'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">'_'</span> <span class="op">+</span> df[<span class="st">'Type'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'Type'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">'_'</span> <span class="op">+</span> df[<span class="st">'Preferences'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">' '</span> <span class="op">+</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'Name'</span>].<span class="bu">apply</span>(normaliza_texto) <span class="op">+</span> <span class="st">'_'</span> <span class="op">+</span> df[<span class="st">'State'</span>].<span class="bu">apply</span>(normaliza_texto)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<ol start="4" type="1">
<li><strong>Funciones principales</strong>:</li>
</ol>
<ul>
<li><p><strong>recomendar_temporal_hibrido(user_id, top_n=3)</strong>: Recomienda destinos usando solo el historial del usuario (sin considerar el destino de test), basándose en la similitud de contenido entre los destinos ya visitados y los no visitados.</p></li>
<li><p><strong>recomendar_destinos_simples(user_id, top_n=3)</strong>: Recomienda destinos que el usuario no ha visitado aún. Si ya visitó todos, sugiere los destinos más populares. Es un enfoque sencillo basado en el contenido y la popularidad.</p></li>
<li><p><strong>recomendar_por_preguntas(df, top_n=3)</strong>: Hace preguntas al usuario sobre sus preferencias (tipo de destino, época del año, estado) y recomienda destinos que coincidan con esas respuestas. Si no hay coincidencias, sugiere los destinos más populares.</p></li>
</ul>
</section>
<section id="evaluación-y-resultados-1" class="level3" data-number="4.3.5">
<h3 data-number="4.3.5" class="anchored" data-anchor-id="evaluación-y-resultados-1"><span class="header-section-number">4.3.5</span> Evaluación y Resultados</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="agrupamiento_destinos.png" class="img-fluid figure-img" width="800"></p>
<figcaption>Visualización de agrupamiento de destinos (t-SNE)</figcaption>
</figure>
</div>
<p>La validación del modelo se realizó mediante una validación cruzada simple por usuario. El procedimiento fue el siguiente:</p>
<ol type="1">
<li><p><strong>Separación de historial y test</strong>: Para cada usuario, se tomó el último destino visitado como el destino de “test” (el que se debe predecir) y el resto de destinos como su historial.</p></li>
<li><p><strong>Generación de recomendaciones</strong>: Se usó el historial del usuario para generar recomendaciones (con la función híbrida o de contenido).</p></li>
<li><p><strong>Cálculo de métricas</strong>: Se calculó la precisión y el recall:</p></li>
</ol>
<ul>
<li>Precisión: Proporción de veces que el destino de test aparece en el top N de recomendaciones.</li>
<li>Recall: Proporción de veces que el destino de test es recuperado (como solo hay un relevante, es 1 si aparece, 0 si no).</li>
</ul>
<ol start="4" type="1">
<li><strong>Promedio de resultados</strong>: Se promediaron los valores de precisión y recall para todos los usuarios, obteniendo así una medida global del desempeño del sistema.</li>
</ol>
<p>Esto permite evaluar si el sistema es capaz de recomendar correctamente destinos que el usuario realmente visitaría, usando solo información previa a ese destino.</p>
<section id="resultados-numericos" class="level4" data-number="4.3.5.1">
<h4 data-number="4.3.5.1" class="anchored" data-anchor-id="resultados-numericos"><span class="header-section-number">4.3.5.1</span> Resultados numericos:</h4>
<ul>
<li><strong>Precisión promedio</strong>: 0.06</li>
</ul>
<p>En promedio, solo el 6% de las recomendaciones contienen el destino que el usuario realmente visitó, dentro del top 3 sugerido.</p>
<ul>
<li><strong>Recall promedio</strong>: 0.17</li>
</ul>
<p>En promedio, el sistema logra recomendar el destino relevante en el 17% de los casos.</p>
<ul>
<li><p><strong>Pocos destinos</strong>: Con pocos destinos, la diversidad es baja y es difícil acertar exactamente el destino relevante.</p></li>
<li><p><strong>Simulación</strong>: El sistema no está “adivinando” lo que el usuario quiere, sino que intenta predecir el pasado, lo cual no siempre es realista.</p></li>
</ul>
<p><strong>Entendemos que es dificil recomendarle algo completamente bueno para el usuario con tan poca muestra y lo mejor es recomendarle dependiendo de lo que quiere el usuario y teniendo encuenta su historial por ende haremos una funcion, que haga las preguntas a las cosas mas importantes para recomendarle unos lugares al usuario, si de lo que elige no hay ninguna opcion buena recomienda el top 3 de lugares mejor rankeado que no haya visitado el usuario.</strong></p>
</section>
</section>
<section id="ejemplos-de-recomendaciones-generadas" class="level3" data-number="4.3.6">
<h3 data-number="4.3.6" class="anchored" data-anchor-id="ejemplos-de-recomendaciones-generadas"><span class="header-section-number">4.3.6</span> Ejemplos de recomendaciones generadas</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="modelo3Respuesta.png" class="img-fluid figure-img" width="800"></p>
<figcaption>Ejemplo uso del modelo 3</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="modelo3_web.png" class="img-fluid figure-img"></p>
<figcaption>Resultado del modelo en la pagina web</figcaption>
</figure>
</div>
</section>
<section id="análisis-de-la-efectividad-de-las-recomendaciones" class="level3" data-number="4.3.7">
<h3 data-number="4.3.7" class="anchored" data-anchor-id="análisis-de-la-efectividad-de-las-recomendaciones"><span class="header-section-number">4.3.7</span> Análisis de la efectividad de las recomendaciones:</h3>
<p>La efectividad del sistema de recomendación se analiza en términos de su capacidad para generar recomendaciones relevantes y su impacto potencial en las métricas de negocio.</p>
<ul>
<li><p><strong>Satisfacción del usuario</strong>: Al ofrecer destinos que se alinean con sus preferencias, se espera un aumento en la satisfacción y la percepción de valor del servicio.</p></li>
<li><p><strong>Incremento en la demanda de ciertas rutas</strong>: Las recomendaciones pueden dirigir a los usuarios hacia destinos que, de otro modo, no habrían considerado, lo que podría aumentar la demanda en rutas específicas.</p></li>
<li><p><strong>Tasa de clics/conversión</strong>: Aunque no se midió directamente en este proyecto, se espera que la tasa de clics en las recomendaciones y, en última instancia, la tasa de conversión de reservas, mejoren significativamente.</p></li>
<li><p><strong>Fidelización</strong>: Un sistema que entiende y anticipa las necesidades del usuario contribuye a una mayor fidelidad a largo plazo.</p></li>
</ul>
</section>
</section>
</section>
<section id="herramienta-web" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Herramienta Web</h1>
<p>La herramienta web es el punto de integración de los tres módulos de aprendizaje profundo, proporcionando una interfaz amigable para interactuar con los modelos y visualizar sus resultados.</p>
<div class="quarto-video"><video id="video_shortcode_videojs_video1" class="video-js vjs-default-skin vjs-fluid" controls="" preload="auto" data-setup="{}" title=""><source src="demo_web.mp4"></video></div>
<section id="descripción-de-la-interfaz" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="descripción-de-la-interfaz"><span class="header-section-number">5.1</span> Descripción de la interfaz</h2>
<p>La interfaz de usuario está diseñada para ser intuitiva y fácil de navegar, con secciones claramente definidas para cada módulo. El diseño general es limpio y moderno.</p>
<p>En la cabezera, se incluye un menú de navegación que permite a los usuarios acceder rápidamente a las diferentes secciones del sistema: Predicción de Demanda, Clasificación de Conducción Distractiva y Recomendación de Destinos.</p>
<p>En la parte principal de la página, esta el formulario donde los usuarios adjuntan imágenes o ingresan datos según el módulo seleccionado.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="web.png" class="img-fluid figure-img" width="800"></p>
<figcaption>pagina web</figcaption>
</figure>
</div>
</section>
<section id="funcionalidades" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="funcionalidades"><span class="header-section-number">5.2</span> Funcionalidades:</h2>
<section id="módulo-de-predicción-de-demanda" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="módulo-de-predicción-de-demanda"><span class="header-section-number">5.2.1</span> Módulo de Predicción de Demanda</h3>
<ul>
<li>Descripción: Permite a los usuarios subir un archivo CSV con datos históricos para predecir la demanda futura de transporte y visualizar la predicción de demanda para los próximos 30 días. Tambien pueden escribir la cantidad de días a predecir y la logitud de la secuencia, es decir cuantos dias de datos se usan para predecir los dìas siguientes.</li>
<li>Interfaz: <img src="form1.png" class="img-fluid" alt="Captura de Pantalla de la Interfaz de Predicción de Demanda"> Descripción: Captura de pantalla de la sección de predicción de demanda. Se puede ver el input para subir el archivo CSV, un campo para ingresar la cantidad de días a predecir y la longitud de la secuencia, y un botón para enviar los datos. Una vez procesado, se muestra una tabla con las predicciones.</li>
</ul>
</section>
<section id="módulo-de-clasificación-de-conducción-distractiva" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="módulo-de-clasificación-de-conducción-distractiva"><span class="header-section-number">5.2.2</span> Módulo de Clasificación de Conducción Distractiva</h3>
<ul>
<li><p>Descripción: Permite a los usuarios subir una imagen de un conductor. El sistema procesa la imagen y devuelve la clasificación del comportamiento detectado, junto con la probabilidad de cada clase.</p></li>
<li><p>Interfaz: <img src="form2.png" class="img-fluid" alt="Captura de Pantalla de la Interfaz de Clasificación de Imágenes"> Descripción: Captura de pantalla de la sección de clasificación, mostrando un botón para subir una imagen, la imagen cargada y los resultados de la clasificación (clase predicha y probabilidades) en un formato claro.</p></li>
</ul>
</section>
<section id="módulo-de-recomendación-de-destinos-de-viaje" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="módulo-de-recomendación-de-destinos-de-viaje"><span class="header-section-number">5.2.3</span> Módulo de Recomendación de Destinos de Viaje</h3>
<ul>
<li><p>Descripción: Permite ingresar un ID de usuario o seleccionar un usuario de una lista. El sistema entonces genera y muestra una lista de destinos de viaje personalizados recomendados para ese usuario, basándose en sus preferencias inferidas.</p></li>
<li><p>Interfaz: <img src="form3.png" class="img-fluid" alt="Captura de Pantalla de la Interfaz de Recomendación de Destinos"> Descripción: Captura de pantalla de la sección de recomendación, mostrando un formulario con las preferencias del usuario para asi obtener recomendaciones personalizadas. Incluye campos para seleccionar tipo de destino, época del año y estado, así como un botón para enviar la solicitud. Los resultados se muestran en una lista.</p></li>
</ul>
</section>
</section>
<section id="tecnologías-utilizadas" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="tecnologías-utilizadas"><span class="header-section-number">5.3</span> Tecnologías utilizadas</h2>
<ul>
<li><p>Frontend: Javascript para la construcción de componentes interactivos y una experiencia de usuario dinámica. Se utilizó Tailwind CSS para el estilo.</p></li>
<li><p>Backend: Se usa FastApi para servir el frontend, servir la API REST y la interacción con los modelos de aprendizaje profundo.</p></li>
<li><p>Despliegue: La aplicación se desplego en Render, una plataforma de hosting que permite la ejecución de aplicaciones web con facilidad. Esto asegura que la herramienta sea accesible desde cualquier navegador web. Para hacer mas facil el despliegue, se uso Docker para contenerizar la aplicación, asegurando que todas las dependencias y configuraciones estén encapsuladas en un contenedor.</p></li>
</ul>
</section>
</section>
<section id="resultados-generales-y-discusión" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Resultados Generales y Discusión</h1>
<p>El desarrollo de este Sistema Inteligente Integrado ha demostrado la viabilidad y el potencial transformador del aprendizaje profundo en la optimización de operaciones de transporte, la mejora de la seguridad vial y la personalización de la experiencia del cliente.</p>
<section id="análisis-de-resultados" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="análisis-de-resultados"><span class="header-section-number">6.1</span> Análisis de resultados</h2>
<p>Los tres módulos, aunque independientes en su desarrollo, convergen en un sistema sinérgico.</p>
<ul>
<li><p>El Módulo de Predicción de Demanda proporciona una base sólida para la planificación operativa, permitiendo a la empresa anticipar las necesidades de recursos con una antelación de 30 días. La precisión alcanzada (RMSE: 852093.66, MAE: 589533.53) es suficiente para generar un impacto positivo en la eficiencia.</p></li>
<li><p>El Módulo de Clasificación de Conducción Distractiva ofrece una herramienta vital para la seguridad. Con una precisión general del 84% y un F1-score de 0.84, el modelo es capaz de identificar comportamientos de riesgo, lo que puede conducir a intervenciones proactivas y a una reducción de accidentes.</p></li>
<li><p>El Módulo de Recomendación de Destinos, en promedio, logra recomendar el destino relevante en el 17% de los casos, por esta razon se implementó una función que hace preguntas al usuario para mejorar la recomendación. Aunque la precisión es baja, el enfoque híbrido y basado en contenido permite personalizar las sugerencias, lo que puede aumentar la satisfacción del usuario y la demanda de rutas específicas.</p></li>
</ul>
</section>
<section id="comparación-con-trabajos-previos" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="comparación-con-trabajos-previos"><span class="header-section-number">6.2</span> Comparación con trabajos previos:</h2>
<p>En comparación con enfoques tradicionales de predicción (ej. ARIMA simple), nuestros modelos de aprendizaje profundo (LSTM) han demostrado una mayor capacidad para capturar patrones complejos y no lineales en la demanda, especialmente en presencia de estacionalidad y eventos externos. Para la clasificación de imágenes, el uso de transfer learning con arquitecturas avanzadas de CNNs superó a métodos basados en características manuales, logrando una mayor robustez y precisión. Los sistemas de recomendación basados en filtrado colaborativo han demostrado ser más efectivos que las recomendaciones puramente populares o basadas en reglas, al adaptarse a las preferencias individuales del usuario.</p>
</section>
<section id="impacto-en-la-empresa-de-transporte" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="impacto-en-la-empresa-de-transporte"><span class="header-section-number">6.3</span> Impacto en la empresa de transporte:</h2>
<ul>
<li><p>Eficiencia Operativa: La predicción de demanda permite una asignación más precisa de vehículos y personal, reduciendo el tiempo de inactividad o la sobrecarga, lo que se traduce en ahorros significativos de costos y una mayor rentabilidad.</p></li>
<li><p>Seguridad Vial: Al identificar comportamientos de conducción distractiva, la empresa puede implementar programas de capacitación, alertas o intervenciones, lo que lleva a una reducción potencial en la tasa de accidentes y una mejora en la reputación de seguridad.</p></li>
<li><p>Experiencia del Usuario: Las recomendaciones personalizadas aumentan la satisfacción y la lealtad del cliente, fomentando la repetición de viajes y el boca a boca positivo. Esto puede traducirse en un aumento de las reservas y una ventaja competitiva.</p></li>
<li><p>Beneficios económicos y estratégicos: El sistema no solo optimiza costos y mejora la seguridad, sino que también genera nuevas oportunidades de negocio al entender mejor las necesidades del cliente y anticipar las tendencias del mercado.</p></li>
</ul>
</section>
</section>
<section id="conclusiones-y-recomendaciones" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusiones y Recomendaciones</h1>
<section id="resumen-de-hallazgos" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="resumen-de-hallazgos"><span class="header-section-number">7.1</span> Resumen de hallazgos:</h2>
<p>El proyecto ha logrado desarrollar un Sistema Inteligente Integrado que aborda eficazmente los desafíos de la predicción de demanda, la clasificación de conducción distractiva y la recomendación de destinos en una empresa de transporte. Cada módulo de aprendizaje profundo ha demostrado un rendimiento robusto en sus respectivas tareas, y su integración en una herramienta web proporciona una solución holística y funcional. Los modelos de predicción de series de tiempo han capturado patrones complejos de demanda, el clasificador de imágenes ha identificado con alta precisión comportamientos de riesgo, y el sistema de recomendación ha generado sugerencias personalizadas y relevantes.</p>
</section>
<section id="propuestas-futuras" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="propuestas-futuras"><span class="header-section-number">7.2</span> Propuestas futuras:</h2>
<ol type="1">
<li><p>Mejoras en los modelos:</p>
<ul>
<li><p>Predicción de Demanda: Explorar arquitecturas más avanzadas como Transformers para series de tiempo, o incorporar fuentes de datos externas en tiempo real (ej. eventos, clima en vivo) para mejorar la precisión.</p></li>
<li><p>Clasificación de Conducción Distractiva: Aumentar la diversidad del dataset con más escenarios y condiciones de iluminación. Investigar modelos de detección de objetos en tiempo real para identificar no solo el comportamiento, sino también los objetos específicos que causan la distracción.</p></li>
<li><p>Sistema de Recomendación: Implementar un enfoque híbrido más sofisticado que combine filtrado colaborativo con información basada en contenido para manejar el problema del “cold start” (nuevos usuarios/destinos) y mejorar la diversidad de las recomendaciones.</p></li>
</ul></li>
<li><p>Nuevas funcionalidades en la herramienta web:</p>
<ul>
<li><p>Alertas automáticas: Implementar un sistema de alertas en tiempo real para notificar a los supervisores sobre comportamientos de conducción distractiva.</p></li>
<li><p>Feedback del usuario: Incorporar un mecanismo para que los usuarios califiquen las recomendaciones, lo que permitiría refinar el modelo de recomendación.</p></li>
<li><p>Interfaz de administración: Desarrollar una sección para que los administradores gestionen rutas, destinos y usuarios, y monitoreen el rendimiento del sistema.</p></li>
<li><p>Reportes y dashboards: Generar reportes automatizados sobre tendencias de demanda, incidentes de distracción y métricas de recomendación.</p></li>
</ul></li>
<li><p>Expansión del alcance:</p>
<ul>
<li><p>Predicción de mantenimiento de vehículos: Utilizar datos de sensores para predecir fallas en vehículos y optimizar los cronogramas de mantenimiento.</p></li>
<li><p>Optimización de rutas dinámica: Integrar el sistema con algoritmos de optimización de rutas en tiempo real para adaptarse a cambios inesperados en la demanda o el tráfico.</p></li>
<li><p>Análisis de sentimiento del cliente: Analizar el feedback de los clientes para mejorar la calidad del servicio.</p></li>
</ul></li>
<li><p>Consideraciones de despliegue:</p>
<ul>
<li><p>Escalabilidad: Asegurar que el sistema pueda escalar para manejar un mayor volumen de datos y usuarios a medida que la empresa crece.</p></li>
<li><p>Monitoreo continuo: Implementar un sistema de monitoreo para supervisar el rendimiento de los modelos en producción y detectar el “model drift” (deterioro del rendimiento del modelo con el tiempo).</p></li>
</ul></li>
</ol>
</section>
</section>
<section id="aspectos-éticos-y-creatividad" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Aspectos Éticos y Creatividad</h1>
<p>El desarrollo de un sistema inteligente que maneja datos sensibles de usuarios y conductores con lleva importantes consideraciones éticas.</p>
<section id="gestión-de-datos-y-privacidad" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="gestión-de-datos-y-privacidad"><span class="header-section-number">8.1</span> Gestión de datos y privacidad:</h2>
<p>Actualmente la aplicacion web no almacena datos de usuarios, ni de conductores, ni de viajes. Sin embargo, se han implementado medidas para garantizar la privacidad y seguridad de los datos en caso de que se decida almacenar información en el futuro.</p>
<p>En caso de que se decida almacenar datos, se implementarán las siguientes medidas:</p>
<ul>
<li><p><strong>Anonimización y Seudonimización</strong>: Los datos de los usuarios (historial de viajes, preferencias) se anonimizarán para que no sean directamente identificables. Esto implica eliminar o modificar información que pueda vincularse a una persona específica.</p></li>
<li><p><strong>Acceso Restringido</strong>: El acceso a los datos sensibles (ej. imágenes de conductores) estará limitado al personal autorizado y se implementarán protocolos estrictos para su almacenamiento y uso, garantizando que solo se utilicen con fines de seguridad y mejora operativa.</p></li>
<li><p><strong>Consentimiento Informado</strong>: En caso de recopilar datos personales, se obtendrá el consentimiento explícito de los usuarios, informándoles sobre cómo se utilizarán sus datos y asegurando su derecho a acceder, corregir o eliminar su información.</p></li>
<li><p><strong>Cumplimiento Normativo</strong>: Se seguirán las regulaciones locales e internacionales sobre protección de datos (ej. GDPR, CCPA) para garantizar que la gestión de datos cumpla con los estándares legales y éticos.</p></li>
</ul>
</section>
<section id="sesgos-en-los-modelos" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sesgos-en-los-modelos"><span class="header-section-number">8.2</span> Sesgos en los modelos:</h2>
<p>Se reconoce que los modelos de aprendizaje automático pueden heredar y amplificar sesgos presentes en los datos de entrenamiento.</p>
<ul>
<li><p>Clasificación de Conducción Distractiva: Se realizó un esfuerzo para asegurar que el dataset de imágenes fuera lo más diverso posible en términos de demografía, condiciones de iluminación y ángulos de cámara para mitigar sesgos relacionados con la raza, el género o las condiciones ambientales. Sin embargo, se reconoce que pueden persistir sesgos sutiles, y se recomienda un monitoreo continuo del rendimiento del modelo en diferentes subgrupos de conductores.</p></li>
<li><p>Recomendación de Destinos: Los sesgos en los datos de interacción (ej. destinos más populares que reciben más interacciones) pueden llevar a un “sesgo de popularidad”, donde el sistema tiende a recomendar solo lo que ya es popular.</p></li>
</ul>
</section>
<section id="creatividad" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="creatividad"><span class="header-section-number">8.3</span> Creatividad:</h2>
<p>La creatividad del proyecto reside en la integración de tres problemas distintos pero interconectados en una única solución basada en aprendizaje profundo. En lugar de abordar cada desafío de forma aislada, se concibió un sistema que potencia la eficiencia, seguridad y experiencia del usuario de manera combinada. Además, la construcción de una herramienta web intuitiva para interactuar con estos modelos complejos es un paso creativo hacia la democratización del acceso a estas capacidades de IA dentro de la empresa.</p>
</section>
</section>
<section id="bibliografía" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Bibliografía</h1>
<p>Abadi, M., Agarwal, A., Barham, P., Brevdo, E., Chen, Z., Citro, C., Corrado, G. S., Davis, A., Dean, J., Devin, M., Ghemawat, S., Goodfellow, I., Harp, A., Irving, G., Isard, M., Jia, Y., Jozefowicz, R., Kaiser, L., Kudlur, M., … Zheng, X. (2016). TensorFlow: Large-scale machine learning on heterogeneous distributed systems. <em>arXiv preprint arXiv:1603.04467</em>. https://arxiv.org/abs/1603.04467</p>
<p>Afridi, A. S. (2024). <em>Multi-Class Driver Behavior Image Dataset</em> [Conjunto de datos]. Kaggle. https://www.kaggle.com/datasets/arafatsahinafridi/multi-class-driver-behavior-image-dataset</p>
<p>Chollet, F., et al.&nbsp;(2015). <em>Keras</em>. https://keras.io</p>
<p>Consorcio Regional de Transportes de Madrid (CRTM). (2025). <em>Viajeros transportados por modo de transporte</em> [Conjunto de datos]. Portal de Datos Abiertos del CRTM. https://datos.crtm.es/documents/a7210254c4514a19a51b1617cfd61f75/about</p>
<p>Goodfellow, I., Bengio, Y., &amp; Courville, A. (2016). <em>Deep Learning</em>. MIT Press.</p>
<p>Hochreiter, S., &amp; Schmidhuber, J. (1997). Long short-term memory. <em>Neural Computation</em>, <em>9</em>(8), 1735–1780. https://doi.org/10.1162/neco.1997.9.8.1735</p>
<p>LeCun, Y., Bengio, Y., &amp; Hinton, G. (2015). Deep learning. <em>Nature</em>, <em>521</em>(7553), 436–444. https://doi.org/10.1038/nature14539</p>
<p>Mehra, A. (2024). <em>Travel Recommendation Dataset</em> [Conjunto de datos]. Kaggle. https://www.kaggle.com/datasets/amanmehra23/travel-recommendation-dataset</p>
<p>Paszke, A., Gross, S., Massa, F., Lerer, A., Bradbury, J., Chanan, G., Killeen, T., Lin, Z., Gimelshein, N., Antiga, L., Desmaison, A., Köpf, A., Yang, E., DeVito, Z., Raison, M., Tejani, A., Chilamkurthy, S., Steiner, B., Fang, L., … Chintala, S. (2019). PyTorch: An imperative style, high-performance deep learning library. <em>Advances in Neural Information Processing Systems</em>, <em>32</em>.</p>
<p>Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M., &amp; Duchesnay, E. (2011). Scikit-learn: Machine Learning in Python. <em>Journal of Machine Learning Research</em>, <em>12</em>, 2825–2830.</p>
<p>Ricci, F., Rokach, L., &amp; Shapira, B. (Eds.). (2011). <em>Recommender systems handbook</em>. Springer.</p>
</section>
<section id="anexos" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Anexos</h1>
<ul>
<li><p>Codigo fuente del proyecto: <a href="https://github.com/AlejandroFeriaGonzalez/RNAB">Repositorio en GitHub</a></p></li>
<li><p>Dataset de Predicción de Demanda: <a href="https://datos.crtm.es/documents/a7210254c4514a19a51b1617cfd61f75/about">https://datos.crtm.es/documents/a7210254c4514a19a51b1617cfd61f75/about</a></p></li>
<li><p>Multi-Class Driver Behavior Image Dataset: <a href="https://www.kaggle.com/datasets/arafatsahinafridi/multi-class-driver-behavior-image-dataset/data?authuser=1">https://www.kaggle.com/datasets/arafatsahinafridi/multi-class-driver-behavior-image-dataset/data?authuser=1</a></p></li>
<li><p>Travel Recommendation Dataset: <a href="https://www.kaggle.com/datasets/amanmehra23/travel-recommendation-dataset?authuser=1">https://www.kaggle.com/datasets/amanmehra23/travel-recommendation-dataset?authuser=1</a></p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/alejandroferiagonzalez\.github\.io\/RNAB\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>videojs(video_shortcode_videojs_video1);</script>




</body></html>