project:
  type: website

website:
  title: "Redes Neuronales y Algoritmos Bioinspirados."
  site-url: https://alejandroferiagonzalez.github.io/RNAB/
  description: "Un blog sobre redes neuronales y algoritmos bioinspirados."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - solar
      - brand
    css: styles.css



